### ISSUE TITLE
Add a JSON Array SerDe

### ISSUE THREAD

**Issue by helpermethod** [spring-projects/spring-kafka#1133]
When building a Kafka Streams application, you often have to group and aggregate some events into a List of events, possibly to join them afterwards with another event stream.

While you could wrap the list into an class, that makes for some very ugly code when accessing / modifying that list e.g.

    reviews.getEntries().add(review);

instead of

    reviews.add(review);

I've already implemented a rough draft of a JsonArraySerde which converts a JSON array to a List<T> (where T is the targetType) and vice versa.

A basic implementation can be found here:

https://github.com/helpermethod/spring-kafka/commit/ac02464daf57dd6461bd30b6440e125dc2509ae7

**Comment by artembilan** [comment]
>  JsonArraySerde which converts a JSON array to a List


I don't think it is a serialization layer responsibility. 
What if I'm not going to use a JSON, but plain old Java serialization?
Should I implement there something else to meet your `List` requirements when we indeed provide an array?
Should that be as a part of your stream processing flow where you have some *transform* to convert an array into a list?

Why do you ask Spring Kafka to do that for you so?
Have you reached Apache Kafka community on the matter?
Isn't your concern should be much broader than Spring Kafka?

Anyway I think this is *Won't Fix*, *Invalid*. 
It is just an abuse of the serialization layer and must be implemented in the target application since it sounds more like a business requirement than technical issue of the framework.

**Comment by helpermethod** [comment]
Hm, I guess that makes sense. As you said, this is probably something which should be discussed in some other medium. Thanks for the answer, closing the issue for now.
