### ISSUE TITLE
CVE-2018-17196

### ISSUE THREAD

**Issue by antolantic** [spring-projects/spring-kafka#1170]
**Affects Version(s):** \at least <=2.2.8

CVE report
A CVE has been updated on 07/18/2019 : https://nvd.nist.gov/vuln/detail/CVE-2018-17196
This is affected current 2.2.x branch of spring-kafka
Is there any work on use 2.1.1 kafka (first version with vulnerabilty fixed) with spring-kafka 2.2.x branch ?

**Comment by artembilan** [comment]
Our current `master` (Spring Kafka 2.3) is already on Kafka Client `2.3.0`.
We can't upgrade all other our supported branches to the latest Kafka Client (even if it is `2.1.1`).

You should consider to upgrade dependencies in your project manually.

Also, since it is not a Spring Kafka issue, I don't see a reason to worry about some changes in this project.
The transitive dependency must be managed in the target project to mitigate a mentioned vulnerability.

I'm closing this one and removing since it is not good to say in the public that there is a security vulnerability.
