### ISSUE TITLE
How MANUAL_IMMEDIATE[_SYNC] really works?

### ISSUE THREAD

**Issue by dmachlin** [spring-projects/spring-kafka#118]
Hi,
As i understand this, manual commits are executed via `KafkaMessageListenerContainer.handleManualAcks()` that is called in `run()` in the same class after polling the records, but only in case any acks exist already.
But, after the first poll, no ack's in the queue exist as the listeners weren't invoked yet.
If there is only **one poll** with data (as happens in tests often), how exactly manual acks are sent?
Also, if i understand correctly, MANUAL_IMMEDIATE AckMode, doesn't guarantee that the ack really happened when the listener method called `acknowledge()`, right?

Thanks!

**Comment by mbogoevici** [comment]
Hi @dmachlin,

Hi,

A couple of answers:

> If there is only one poll with data (as happens in tests often), how exactly manual acks are sent?

On normal shutdown (i.e. during `stop()`, once the `ListenerConsumer` has stopped executing the poll loop) we flush the pending acks - so everything else that is left outside the loop is still handled. The `IMMEDIATE` part means that we won't for a number of acks to accumulate or a specific time to pass (the latter is necessary in order to reduce chatter around commits and increase throughput, especially with sync commits).

> Also, if i understand correctly, MANUAL_IMMEDIATE AckMode, doesn't guarantee that the ack really happened when the listener method called acknowledge(), right?

Yes, because acknowledgment needs to be done by the consumer thread (the consumer is not thread-safe) so the listener cannot call `acknowledge()` by itself.

**Comment by garyrussell** [comment]
Actually, I don't think there's much (any?) difference between manual and manual immediate now we fixed the pause/resume stuff - since in all cases, `acknowledge` [queues the ack and then wakes the consumer thread](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L816).

Originally, manual acks were done at the end of the batch and manual_immediate did them directly from `acknowledge`.

We could probably also get rid of the _SYNC variant now, since we also have the `syncCommits` flag.

Such a change would likely mean putting out a second release candidate, though, which would delay the GA, so maybe we should defer it to 1.1.

**Comment by artembilan** [comment]
Since there was no any bug reports (yet), we really can consider this as an improvement and move to `1.1` version.

**Comment by mbogoevici** [comment]
I haven't looked at the code in detail before posting, but this seems to have changed indeed.

We need to change this then:

```
		/**
		 * Same as {@link #COUNT_TIME} except for pending manual acks.
		 */
		MANUAL,
```

It would make more sense to me though to restore this to do what it says it does. Even in manual mode, we should be able to accumulate acks and only make periodic calls.

**Comment by dmachlin** [comment]
> On normal shutdown (i.e. after invoking stop(), once the ListenerConsumer has stopped executing the poll loop) we flush the pending acks - so everything else that is left outside the loop is still handled.

I don't see any reason to wait for processing the last pending acks only for the normal shutdown that may never happen.
This might cause several hard to detect bugs like:
When using Kafka as a way of passing messages asynchronously between services, which I believe is a common use case, at time your work in bluks, so process A sends X messages to process B once a day, and when B will finish consuming from the topic it will do some bulk related work.
This work will succeed but the acks for the final poll will remain in the acks queue until A sends again or B dies normally.
Now lets say process B crashes, it will restart and consume the messages from the last poll again and will consider it as a full bulk. 
Or it crashes and in the meantime process A sent another X messages so upon B's recovery it will process X+(last poll's) messages.

I think that `handleManualAcks()` should run every time and not only when records are fetched, just like 
```
if (!this.autoCommit) {
    processCommits();
}
```
So maybe move `handleManualAcks()` into `processCommits`?

**Comment by dmachlin** [comment]
Another issue with the above logic is that the consumer can never know it finished processing all the messages in the topic as it's offset will always be behind the log offset.

**Comment by mbogoevici** [comment]
> So maybe move `handleManualAcks()` into `processCommits`?

Decoupling the handling of the acks of the receipt of messages could be a good improvement.

**Comment by artembilan** [comment]
> So maybe move handleManualAcks() into processCommits?

Addressed with https://github.com/spring-projects/spring-kafka/commit/be2e6ce984cf9173261b542fbb76e1b113498759
