### ISSUE TITLE
KafkaStreamsConfiguration converts all values to String

### ISSUE THREAD

**Issue by lendle** [spring-projects/spring-kafka#1228]
**Affects Version(s):** 2.2.8

My use case: I have implemented a `org.apache.kafka.common.metrics.MetricsReporter` that depends on a spring managed bean (a micrometer `MeterRegistry` bean in this case). KafkaStreams instantiates the metrics reporter with `AbstractConfig#getConfiguredInstances`, so I can only pass dependencies to the instantiated object via `Configurable#configure`. My solution so far has been to pass the instantiated object to `Configurable#configure` with a custom key in the config map. Because `KafkaStreamsConfiguration` converts configuration values to string, I cannot get access to it in `configure`. 

As a workaround, I can use the deprecated `org.springframework.kafka.config.StreamsBuilderFactoryBean#StreamsBuilderFactoryBean(java.util.Map<java.lang.String,java.lang.Object>)`, but I assume this will eventually be removed.

This behavior appears to be intentional, but I do not understand why. As far as I know there is no plan to require on the Kafka Streams side that configuration property values be strings. Even in the api docs for the current version (2.3) of kafka streams, the configuration properties object in the example contains non-string values: https://kafka.apache.org/23/javadoc/org/apache/kafka/streams/KafkaStreams.html, e.g. the value for "default.key.serde" is a `Class`.

**Comment by artembilan** [comment]
This has been fixed with this: https://github.com/spring-projects/spring-kafka/issues/1082

Tomorrow we are going to release 2.3.0.RC1 with GA in a couple weeks. 
Let us know if that works for you!

Although I'm not sure that we are going to back-port such a fix into `2.2.x`: it is going to be as a breaking change.

On the other hand you can extend `KafkaStreamsConfiguration` and override its `asProperties()`  and feed that custom one as a bean for the `StreamsBuilderFactoryBean` 😄

**Comment by garyrussell** [comment]
We were thrown off by the deprecation of the `StreamsConfig` CTOR in favor of the CTOR that takes `Properties`. It turns out that the use a Properties is a bit of an abuse in that they are not using it as a true `Properties` object, but the HashTable that it extends; unfortunate and misleading, really.

As Artem pointed out, this bit us elsewhere, and we have now reflected that abuse in the 2.3 code which now returns the `Properties` unchanged; you can safely use the CTOR that takes a Map and move to the Properties when 2.3 is released.

**Comment by lendle** [comment]
Ah I see, thank you for the context.

**Comment by artembilan** [comment]
So, closing as fixed with #1082 and with the provided workaround
