### ISSUE TITLE
SeekToCurrentErrorHandler maxFailures doesn't work when concurrency level is less than partition number

### ISSUE THREAD

**Issue by tianhao-au** [spring-projects/spring-kafka#1232]
I am using spring kafka 2.2.7 and my consumer configuration code is following:

```
factory.setConcurrency(1);
    SeekToCurrentErrorHandler errorHandler =
        new SeekToCurrentErrorHandler((record, exception) -> {
          LOGGER.info("***in error handler data, {}", record);
        }, 3);
    factory.setErrorHandler(errorHandler);
```

So, if I have an exception happening in my listener, the consumer will retry the failed message forever even I config the maxFailures in the configuration if the concurrency level I specified is less than the partition counts for my topic. 

It will only work if i send the message one by one at least a second interval. If I send the message as a batch, the behaviour wouldn't work. Unless I restart the consumer and it will work properly.

**Comment by artembilan** [comment]
Related SO question: https://stackoverflow.com/questions/57889424/spring-kafka-seektocurrenterrorhandler-maxfailures-doesnt-work-when-concurrency.

So, closing this one in favor of that until we really agree that it is a bug

**Comment by tianhao-au** [comment]
@artembilan Can you please explain why this happening? I can't see any docs related to this.

Would be great if you can answer either here or in SO before close this question? Instead of explaining nothing.

Thanks.

**Comment by artembilan** [comment]
I can't explain yet, but it is kinda spam for us to handle questions here and there.
We use GH only for bug reports and new features requests.
I wouldn't close this one if there was no SO question.
More over you asked me about this in many places already.

Please, bare with our working processes and keep in mind that we have not only you to support.

Thanks for understanding.


Let me drink some morning coffee, investigate your problem and come back to you on SO! Since it still sounds for me like a question.
Instead of complaining that you don't like our support process...
