### ISSUE TITLE
Kafka Streams create store support

### ISSUE THREAD

**Issue by nyilmaz** [spring-projects/spring-kafka#1236]
Hi there!

I'm trying to achieve adding stores (in my case global one) via `StreamsBuilder`. I think adding state store and global store should be handled inside `StreamsBuilderFactoryBean`. Because those operations do indeed change underlying topology. My first question would be; how can we safely add store to `StreamsBuilder` before it is created here: https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java#L313

I have in mind for usage;

Provide `KafkaStreamsStoreCustomizer`(s) having `customize(StreamsBuilder)` and call this before we initialize `Topology`.

Any comments, suggestions?

**Comment by artembilan** [comment]
I wonder if this is something what can help you from Kafka Streams Binder perspective: https://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/3.0.0.M3/reference/html/spring-cloud-stream-binder-kafka.html#_state_store

Although I won't mind if you provide more context how that `KafkaStreamsStoreCustomizer` could help us.

Thanks

**Comment by nyilmaz** [comment]
Well, it seems the kafka-streams setup occurs inside `KafkaStreamsStreamListenerSetupMethodOrchestrator`. Currently with only spring-kafka and kafka-streams dependencies, I got a custom store working like;

```
@Configuration
class KafkaStreamsConfiguration {

    @Bean("categoryStreamsBuilderFactoryBean")
    @Primary
    public StreamsBuilderFactoryBean streamsBuilderFactoryBean(@Qualifier(CONFIG_BEAN_NAME) StreamsConfig streamsConfig)
        throws Exception {
      StreamsBuilderFactoryBean factoryBean = new StreamsBuilderFactoryBean(streamsConfig);
      factoryBean.setStateRestoreListener(new CategoryStateRestoreListener());
      factoryBean.afterPropertiesSet();
      return factoryBean;
    }
}


@Configuration
class CategoryKafkaStreamsConfiguration {

    private final StreamsBuilder streamsBuilder;

    private final String categoryTopicName;

    private final String categoryStoreName;

    @PostConstruct
    public void init() {
        StoreBuilder<KeyValueStore<Long, Category>> categoryStoreBuilder =
            Stores.keyValueStoreBuilder(inMemoryKeyValueStore(this.categoryStoreName),
                                        Serdes.Long(), CATEGORY_JSON_SERDE);
        streamsBuilder.addGlobalStore(categoryStoreBuilder,
                                      this.categoryTopicName,
                                      Consumed.with(Serdes.Long(), CATEGORY_JSON_SERDE),
                                      () -> new CategoryUpdateProcessor(this.categoryStoreName));
    }
  }

// and use it somewhere
private ReadOnlyKeyValueStore<Long, Category> getStore() {
    return Optional.ofNullable(this.store).orElseGet(() -> {
      KafkaStreams kafkaStreams = factoryBean.getKafkaStreams();
      this.store = kafkaStreams.store(storeName, QueryableStoreTypes.keyValueStore());
      return store;
    });
}
```

Is this approach ok? Or can we reduce the boilerplate code here, just like you pointed at spring-cloud-stream-binder project?

**Comment by sobychacko** [comment]
@nyilmaz In the latest version of the kafka streams binder in spring cloud stream (which is built upon spring-kafka), you can provide a state store bean and the binder will add that to the topology through the stream builder. [Here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/function/KafkaStreamsFunctionStateStoreTests.java#L134) are some examples. See [this](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/integration/KafkaStreamsStateStoreIntegrationTests.java#L256) also for a `StreamListener` based approach. In the 2.x versions, the binder provided an [annotation](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/integration/KafkaStreamsStateStoreIntegrationTests.java#L275) to do the same, but the bean based approach is preferable to the annotations based approach. Currently, the binder doesn't provide any hook for adding global state store, but that is certainly an interesting feature to add. When using Spring Kafka, I think the approach you laid out above seems to be in the right direction, although it looks like the customizer you mentioned can be enhanced to address this.

**Comment by artembilan** [comment]
@nyilmaz,

Thank you for your example to go. Yes, it really sounds like a *boilerplate code* and definitely should be addresses from the Framework perspective for better end-user experience.

@sobychacko,

thank you for your explanation!
Seems for me you already have a solution in the Binder implementaiton.
Wouldn't everybody benefit from having your solution here in Spring Kafka?

I mean contribution is welcome, folks! 😄

**Comment by sobychacko** [comment]
@artembilan That sounds like a good idea. I am afraid it might be too late to do so in the current version. Maybe after the 3.0 release of Spring Cloud Stream, we can go through the things in the binder to see what all we can push down to Spring Kafka.

**Comment by artembilan** [comment]
Well, I think that's OK to keep current API in Binder for a while, but would be great to have something similar for the current Spring Kafka 2.3 version. So, we can utilize it in the next Binder version.
However if we can't make it for this Thursday's release, it is OK to push such a task to the next `2.4` version.

**Comment by nyilmaz** [comment]
@artembilan @sobychacko do you have guys a structure to implement this feature in mind? Or I can provide a blind PR without knowing your requirements.

**Comment by artembilan** [comment]
You provide a PR and we review and everything else whatever would be needed for this work.

Thank you for your proposition!

**Comment by stijnvanbever** [comment]
Hello,

I'm using spring-kafka 2.4.1 and have used `KafkaStreamsInfrastructureCustomizer` to add a state store to the `StreamsBuilder`.

This state store is being used by a custom Kafka `Transformer` that I'm using in a `KStream`.
The `KStream` is defined as a bean in a configuration class.

While running the application I get this exception:
`TopologyException: Invalid topology: StateStore testStateStore is not added yet.`

While debugging I seem to have found the issue.
It seems that the `KafkaStreamsInfrastructureCustomizer` is only being called while starting the Kafka streams inside: `org.springframework.kafka.config.StreamsBuilderFactoryBean#start`.

But here the `StreamsBuilder` is already created and the `KStream` has already been added.

So while going through the debugger at `org.apache.kafka.streams.kstream.internals.InternalStreamsBuilder#buildAndOptimizeTopology(java.util.Properties)` I noticed that the `StreamsSourceNode` was added before the `StateStoreNode` (due to the Customizer only being called while starting instead of at creation time).

This causes the streams to be added first to the Topology and when that one tries to connect the processor to the state store, it cannot find it. (at: `org.apache.kafka.streams.kstream.internals.InternalStreamsBuilder#buildAndOptimizeTopology(java.util.Properties)`).

In the Kafka documentation I also read that you should always define the state stores first before creating streams.

Could it be that I'm missing something here? Or is there a chance that this is not supported?

Thanks in advance!

**Comment by garyrussell** [comment]
@stijnvanbever Can you open a new issue with a small sample that reproduces this?

I think you are saying that `this.infrastructureCustomizer.configureBuilder(builder)` needs to be moved to `createInstance()` so that any streams you build from the builder will already have the customizations applied.
