### ISSUE TITLE
Is it possible to use `spring-kafka-test` without AssertJ?

### ISSUE THREAD

**Issue by levelast** [spring-projects/spring-kafka#1323]
Is it possible to use `spring-kafka-test` without AssertJ?
I've project with kotlin and excluded assertj from `spring-boot-starter-test`, 'cause we use more kotlin-style assert library and code is really messy when you have two strict library at once. Right now after added dependency `spring-kafka-test` and enable it, I've `java.lang.NoClassDefFoundError: org/assertj/core/util/Arrays`. The problem's line of code:
https://github.com/spring-projects/spring-kafka/blob/cda70d4730c77ce8a994631e2fb446798a220e05/spring-kafka-test/src/main/java/org/springframework/kafka/test/condition/EmbeddedKafkaCondition.java#L110
It's strange to use assertj here, but maybe it's not the one problem. 
Is it better to include asstertj to test scope?

Sorry for my English =)

**Comment by garyrussell** [comment]
Thanks; it's a bug (wrong import - probably an artifact of the IDE auto-selecting.

**Comment by artembilan** [comment]
I think we need to revise all the classes in `spring-kafka-test` for an explicit `org.assertj` imports.
For example `KafkaTestUtils` really can be used in the same Kotlin-based tests, but really without an AssertJ import.

Also it looks like the current fix won't let us go too far because an `EmbeddedKafkaBroker` still has that `import static org.assertj.core.api.Assertions.assertThat;`.

I would even say that all those utils have to be without any assertions. This is really a target test responsibility to check data and state explicitly.
