### ISSUE TITLE
SeekToCurrentBatchErrorHandler infinite retry

### ISSUE THREAD

**Issue by stager0909-ray** [spring-projects/spring-kafka#1382]
I use spring-kafka-test:2.3.4.RELEASE and spring-kafka:2.3.4.RELEASE. 

SeekToCurrentBatchErrorHandler and FixedBackOff are used to retry 2 times when an exception occurs in the consumer.
However, 20 retry attempts occurred during a 10 second sleep. Why doesn't FixedBackOff work?

```java
import static org.assertj.core.api.Assertions.assertThat;

import java.util.Map;

import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.common.serialization.IntegerDeserializer;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.kafka.annotation.EnableKafka;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.kafka.config.ConcurrentKafkaListenerContainerFactory;
import org.springframework.kafka.config.KafkaListenerContainerFactory;
import org.springframework.kafka.core.ConsumerFactory;
import org.springframework.kafka.core.DefaultKafkaConsumerFactory;
import org.springframework.kafka.core.DefaultKafkaProducerFactory;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.kafka.core.ProducerFactory;
import org.springframework.kafka.listener.SeekToCurrentBatchErrorHandler;
import org.springframework.kafka.support.KafkaHeaders;
import org.springframework.kafka.support.serializer.JsonDeserializer;
import org.springframework.kafka.support.serializer.JsonSerializer;
import org.springframework.kafka.test.EmbeddedKafkaBroker;
import org.springframework.kafka.test.context.EmbeddedKafka;
import org.springframework.kafka.test.utils.KafkaTestUtils;
import org.springframework.messaging.handler.annotation.Header;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.util.backoff.FixedBackOff;

import lombok.extern.slf4j.Slf4j;

@Slf4j
@RunWith(SpringRunner.class)
@EmbeddedKafka(topics = "sr2", controlledShutdown = true, partitions = 1, count = 1)
@DirtiesContext
public class RetryTests {

    private static final String DEFAULT_TEST_GROUP_ID = "statefulRetry";
    private static int MAX_RETRY = 2;

    @Autowired
    private Config config;

    @Autowired
    private KafkaTemplate<Integer, String> template;

    @Test
    public void testStatefulRetry() throws Exception {
        this.template.send("sr2", "foo");
        Thread.sleep(10000);
        assertThat(this.config.listener1().count).isEqualTo(MAX_RETRY + 1);
    }

    @Configuration
    @EnableKafka
    public static class Config {
        @Autowired
        private EmbeddedKafkaBroker embeddedKafkaBroker;

        @Bean
        public KafkaListenerContainerFactory<?> kafkaListenerContainerFactory() {
            ConcurrentKafkaListenerContainerFactory<Integer, String> factory =
                new ConcurrentKafkaListenerContainerFactory<>();
            factory.setConsumerFactory(consumerFactory());
            factory.setBatchListener(true);
            SeekToCurrentBatchErrorHandler errorHandler = new SeekToCurrentBatchErrorHandler();
            FixedBackOff backOff = new FixedBackOff(500, MAX_RETRY);
            errorHandler.setBackOff(backOff);
            factory.setBatchErrorHandler(errorHandler);
            return factory;
        }

        @Bean
        public ConsumerFactory<Integer, String> consumerFactory() {
            return new DefaultKafkaConsumerFactory<>(consumerConfigs(200),
                new IntegerDeserializer(),
                new JsonDeserializer<>(String.class));
        }

        private Map<String, Object> consumerConfigs(int maxPollRecord) {
            Map<String, Object> consumerProps =
                KafkaTestUtils.consumerProps(DEFAULT_TEST_GROUP_ID, "false", embeddedKafkaBroker);
            consumerProps.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest");
            consumerProps.put(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, maxPollRecord);
            consumerProps.put(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, 300000);
            return consumerProps;
        }

        @Bean
        public KafkaTemplate<Integer, String> template() {
            KafkaTemplate<Integer, String> kafkaTemplate = new KafkaTemplate<>(producerFactory());
            return kafkaTemplate;
        }

        @Bean
        public ProducerFactory<Integer, String> producerFactory() {
            return new DefaultKafkaProducerFactory<>(producerConfigs());
        }

        @Bean
        public Map<String, Object> producerConfigs() {
            Map<String, Object> config = KafkaTestUtils.producerProps(embeddedKafkaBroker);
            config.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, JsonSerializer.class);
            return config;
        }

        @Bean
        public Listener listener1() {
            return new Listener();
        }

    }

    public static class Listener {

        public volatile int count = 0;

        @KafkaListener(topics = "sr2", groupId = "sr1")
        public void listen1(final String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic,
            @Header(KafkaHeaders.RECEIVED_PARTITION_ID) int partition,
            @Header(KafkaHeaders.OFFSET) long offset) {
            count++;
            log.error("consumer throw exception");
            throw new RuntimeException("consumer throw exception");
        }

    }

}
```

result 
`org.opentest4j.AssertionFailedError: 
Expecting:
 <20>
to be equal to:
 <3>
but was not.`

**Comment by garyrussell** [comment]
GitHub issues are for reporting bugs and asking for new features, not for asking questions - use Stack Overflow for that.

It is designed to work this way; batch error handlers have no mechanism to "recover" from a failure, since there is no indication where in the batch the error occurred.

See the javadocs for `setBackOff()`.

	/**
	 * Set a {@link BackOff} to suspend the thread after performing the seek. Since this
	 * error handler can never "recover" after retries are exhausted, if the back off
	 * returns STOP, then the previous interval is used.
	 * @param backOff the back off.
	 * @since 2.3
	 */
	public void setBackOff(BackOff backOff) {
		this.backOff = backOff;
	}

If you want different behavior, use a custom error handler. There has been some discussion about adding an option to send the entire batch to a dead-letter topic, but I doubt that is what most people would want.

When using a batch listener, it's generally better to handle errors in the listener itself since that's the only place that knows which record failed.

**Comment by jbotuck** [comment]
>There has been some discussion about adding an option to send the entire batch to a dead-letter topic, but I doubt that is what most people would want.

That's exactly what I would want

> When using a batch listener, it's generally better to handle errors in the listener itself since that's the only place that knows which record failed.

But doing retry in the listener itself will cause the broker to assume the consumer died

**Comment by garyrussell** [comment]
@jbotuck There is a new feature in 2.3, when using manual acks you can now ack part of the batch and have the rest redelivered after an optional delay.

See [Committing Offsets](https://docs.spring.io/spring-kafka/docs/2.4.3.RELEASE/reference/html/#committing-offsets).

>When using a batch listener, you can specify the index within the batch where the failure occurred. When `nack()` is called, offsets will be committed for records before the index and seeks are performed on the partitions for the failed and discarded records so that they will be redelivered on the next poll(). This is an improvement over the `SeekToCurrentBatchErrorHandler`, which can only seek the entire batch for redelivery.

**Comment by jbotuck** [comment]
Cool, I was not aware of `nack`, but I don't think it will solve my particular problem.

Here's my use case:
I get a batch of records. I want to enrich them with some extra data and then save the enriched records in the db. 

Due to network issues, I want to make a single network call to get the extra data for the entire batch. I make that single call based on the data in the batch (something like "give me all data where id in  `<these ids i got from the batch>`". It is possible that this network call will fail due to a recoverable error (so should retry) or due to bad data related to the ids I'm getting from the batch.

In the latter case I have no way of knowing which id is causing the failure. My preferred strategy here is to retry with backoff a number of times and if it still fails assume there is something wrong with one of the ids in the batch and send the entire batch to the dead-letter topic.

**Comment by garyrussell** [comment]
One problem with conditional retry is there is no guarantee that the redelivered batch will be identical - there may be additional records - and even the redelivered records might be in a different order (if the consumer is assigned multiple partitions) - we had to change the STCEH to handle that situation because the failed record is not necessarily the first record redelivered - see https://github.com/spring-projects/spring-kafka/issues/1234#issuecomment-531920991

So the difficulty of adding stateful retry is that it will be hard to maintain state for the "batch".

One possible solution might be to handle the batch retries within the container itself - catch the exception, then `pause, poll, resume` to consumer (so that Kafka knows we're still alive) and redeliver the same batch up to some number of attempts, then dump the batch to a DLT if retries are exhausted.

**Comment by garyrussell** [comment]
I think I have a way forward. Stay tuned...
