### ISSUE TITLE
Expose valueSerializer and valueDeserializer (and key) as beans.

### ISSUE THREAD

**Issue by sta-szek** [spring-projects/spring-kafka#1387]
🎁 Enhancement

Hi, I have implemented outbox/inbox pattern when it comes to eventing in our application. Basically we just store events in DB before sending/processing.

We use Avro format for storing events, and of course, we use `io.confluent.kafka.serializers.KafkaAvroDeserializer` and `io.confluent.kafka.serializers.KafkaAvroSerializer`.

Having said that, we want to store events in DB using avro format, because when i used JSON (and ObjectMapper) then in complex structures it was losing class information and e.g. `array of (one of A, B, C)` is becoming `array of Objects` which of course is causing deserialization issues. I will not go deep into details.

So next step is, of course, to reuse the serializers/deserializers that are created by kafka / kafka template / kafka producer factory / kafka producer / anything that creates this.

For now the only way to get it is to use reflection:

`kafkaTemplate.getTheProducer().delegate.delegate.valueSerializer`

Double `delegate` because one of them is TracingKafka (we use spring-sleuth)

As you can see this is not portable, unclean shitty way to get them.

Can you help me there? 

(of course the other solution is to configure objectMapper but it is even less portable, please skip this idea)

Thanks :handshake:

**Comment by artembilan** [comment]
The `KafkaTemplate` is based on the `ProducerFactory` where its implementation is a `DefaultKafkaProducerFactory`. And this one has a ctor like this:
```

	/**
	 * Construct a factory with the provided configuration and {@link Serializer}s.
	 * Also configures a {@link #transactionIdPrefix} as a value from the
	 * {@link ProducerConfig#TRANSACTIONAL_ID_CONFIG} if provided.
	 * This config is going to be overridden with a suffix for target {@link Producer} instance.
	 * @param configs the configuration.
	 * @param keySerializer the key {@link Serializer}.
	 * @param valueSerializer the value {@link Serializer}.
	 */
	public DefaultKafkaProducerFactory(Map<String, Object> configs,
			@Nullable Serializer<K> keySerializer,
			@Nullable Serializer<V> valueSerializer) {
```

So, you are good to configure your `KafkaAvroDeserializer` & `KafkaAvroSerializer` over there and reuse those beans whenever you need with your DB.

You don't need to worry about reflection and we don't need to expose those non-KafkaTemplate options.

Does it make sense to you?

**Comment by sta-szek** [comment]
From your point of view it is correct. 
But this is how I "created" them so far:

```
      properties:
        schema.registry.url: http://confluent-cp-schema-registry.kafka.svc.cluster.local:8081
        specific.avro.reader: true
        key.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
```

From my point of view now I would have to dig into internals of kafka and confluent, and figure out how to create serializers, of course with all the related stuff like post-configurations. Also when new version will be released, I need to check if my initialization is done properly, eventually add missing features (addtional post-configurations) on top of it.

I would prefer to have single mechanisms for that -- if you create it, then do it, otherwise force user to do it all the time + put post-configuration on top of user bean. Or am I wrong? :thinking:

**Comment by artembilan** [comment]
We don't create. That's exactly a target Apache Kafka API:
```
KafkaProducer(Map<String, Object> configs, Serializer<K> keySerializer, Serializer<V> valueSerializer)
```

Therefore we just expose in Spring for Apache Kafka whatever is available for in the target Kafka client implementation.
Even if we would be able to expose an API you request, it is still going to be against reflection. Plus consider your situation with that Sleuth proxying. Without a public API in Apache Kafka client, we can't make a reliable public API in Spring for Apache Kafka.
Therefore a way Apache Kafka it suggests via ctor arguments for the `KafkaProducer` instead of configuration properties is the way to go. At least for now.

I mean when you request such a feature in Apache Kafka and it becomes available for any users, we are more than happy to expose such getters in Spring for Apache Kafka.
However I believe that one already belongs to `DefaultKafkaProducerFactory` and `DefaultKafkaConsumerFactory` if that.

Although I would stay with top-level bean configuration instead of non-transparent instantiation in the Kafka client by reflection from the properties.

**Comment by sta-szek** [comment]
Ok, get it! I will go with proposed approach, thanks!
