### ISSUE TITLE
Support bulk processing of messages

### ISSUE THREAD

**Issue by mackahlawat** [spring-projects/spring-kafka#142]
Hi, 

Should there by an API in `MessageListener` to receive bulk records? Currently, once the call returns from `onMessage()`, then record is 'considered' processed, which simulates a blocking pattern. 
The acknowledgement variant of `onMessage()` does provide some relief in this matter, but it imposes a huge ordering requirement on the listener because `acknowledge()` would consider all records in that partition before the current one as processed, which may not be the case in a multi threaded scenario. 

So, I was thinking something like this would help: 
`List<ListenableFuture<?>> onMessage(List<ConsumerRecords<?,?> records)`, and then once the messages are done, (the list of futures is complete), the offsets can be committed (in the batch mode). 
In the TIME mode, on expiration of timer, we can iterate over the list and see which ones are complete and add them to `processedRecords`.

Or may be a variation like `void onMessage(List<ConsumerRecords<?,?> list, Acknowledgement ack)`, with 
`Acknowledgement` having another method `acknowledgement(ConsumerRecord<?,?> cr)`

What do you guys think?

**Comment by adamdec** [comment]
I was also thinking about something similar like having ConsumerRecords and iterate on my own...to have more control over the batch and commit process...lets see what guys from Spring will answer.

**Comment by garyrussell** [comment]
My initial thought when reading this issue was to add another listener type `onMessage(ConsumerRecords)` as @adamdec suggests, but that doesn't solve @mackahlawat 's issue of putting the burden of knowing when/what to commit on the listener (especially when multi-threading the contents of the `ConsumerRecords`).

However, a variation of @mackahlawat 's second suggestion:

    void onMessage(ConsumerRecords, MultiAcknowledgment multiAck)

would do the job where the MultiAck accumulates the individual acks and only commits the offset when all the consumer records have been ack'd.

    MultiAcknowledgment.acknowledge(ConsumerRecord<?, ?>);

However, I'm not sure we could easily provide sophisticated variants of the listener adapters (such as the filtering and retrying adapter) for this type of listener. If we did provide them, they would probably have to apply to the entire batch of messages.

**Comment by adamdec** [comment]
Maybe we could reuse
`AcknowledgingMessageListener` somehow to provide this in best-effort?

`AcknowledgingMessageListener<ConsumerRecords<T>, MultiConsumerAcknowledgment`

?

**Comment by sandeepmalik** [comment]
@garyrussell , @adamdec , for filtering, it should be easier, once we get the bunch of customer records, we can first filter and only pass the list of ones that satisfy the predicate, so this remains seamless to the listener. That's why instead of passing ConsumerRecords object, we should consider using List<ConsumerRecord<?,?>> or Iterable<ConsumerRecord<?,?>>. It could be filtered or unfiltered depending on the filter strategy. 

For retries, we will need to think a bit deeper. One simpler way could be, the we pass a bunch of records, and then include the ones that failed in the next set of records to be processed until x number of times.

**Comment by garyrussell** [comment]
Good point.

**Comment by garyrussell** [comment]
This same question came up at SpringOne last week.
