### ISSUE TITLE
Support for at-most-once delivery with manual acknowledgement

### ISSUE THREAD

**Issue by martindam** [spring-projects/spring-kafka#152]
If the `KafkaMessageListenerContainer` is configured to `MANUAL_IMMEDIATE_SYNC` it is currently not able to guarantee a at-most-once delivery of messages due to the synchronization of the `ListenerInvoker` thread and polling thread. Calling the `Acknowledgement` on a `MANUAL_IMMEDIATE_SYNC` consumer just puts the acknowledgement in the queue and wakes up the polling thread. The thread that called the `Acknowledgement` does however not wait for the commit to be delivered to Kafka (which one would expect from the `ackMode`). If the application crashes at this point, there is a risk of processing a message twice. 

I propose to change the `acks` queue (`BlockingQueue` with `ConsumerRecord`) to contain a wrapper data object that contains the `ConsumerRecord` and a future. When the record is acknowledged (either in a `commitSync` or `commitAsync` on the consumer) the future is set. 
Now, the `ConsumerAcknowledgment` class can now wait for that future after it did the wake up if it is a `MANUAL_IMMEDIATE_SYNC` or ignore it if it is not.

**Comment by artembilan** [comment]
Well, look. Kafka isn't transactional messaging broker and there is even no requirement to commit offests.
And even official Kafka resources recommend to be ready for duplicate messages in our application, since the async nature almost everywhere and persistent topic log in the broker.

Yes, we may consider what you suggest with the `Future` and thread blocking.
But wouldn't it be better to use `FilteringAcknowledgingMessageListenerAdapter` in your application to deal with duplicates if that?

My only concern that blocking the acking thread to wait for the commit of its offset doesn't guarantee duplicates any way. And such an overhead may just make the target solution much complicated, than easier to manage.

WDYT?

**Comment by alessiodm** [comment]
Thank you @artembilan for such a prompt reply.

The official Kafka resources recommend to be ready for duplicate messages because, while the `at-least-once` semantic is fairly simple to obtain (e.g., via retries on the publisher side), the `at-most-once` and the `exactly-once` semantics are definitely trickier - especially the latter. And that’s totally fine.

The duplicates that the official Kafka resources are referring to are at the broker level. While the duplicates that `spring-kafka` would introduce are different and have a different semantic. We shouldn’t mix them up.

If the framework allows for a `MANUAL_IMMEDIATE_SYNC` acknowledgment, I would expect that the currently consumed message will be committed before the listener gets the next message and that action to be completed synchronously. If the next message is a duplicate at the broker level, that’s totally ok to get the same logical message the next time the listener is invoked. But it should never happen that I process the same physical message again after I commit with `MANUAL_IMMEDIATE_SYNC`, and this can actually happen with the current implementation. Duplicating the dispatch of the same physical message from the broker is not semantically the same as dispatching the same logical message that happens to be duplicated in two physical messages in Kafka.

Moreover, we are actually breaking the `synchronous` semantic: the commit operation is not actually synchronous.

I think @martin suggestion is the right way to go, for correctness and for avoiding the framework to introduce shady semantics on top of the broker. Otherwise, I would rename the `MANUAL_IMMEDIATE_SYNC`.

**Comment by artembilan** [comment]
Eh... That's good input, @alessiodm .
Thank you!

Well, what I'm forced to say that we have already removed `MANUAL_IMMEDIATE_SYNC` from the framework. See #131 and its issue #118 for more info.

So, looks like we don't have any premise to even have such a discussion :smile: 

I won't mind if you start to insist for reinstating that mode, but we will need a team discussion if that is really reasonable feature or it would be better if we all will live just without that and just rely on the existing `MANUAL_IMMEDIATE`, which is, eh, `async` by Thread distribution nature.

**Comment by adamdec** [comment]
Hi, I am afraid that there is even more with MANUAL_IMMEDIATE ack mode...I think that there is a live-lock on the listening container when InvokingListener is really fast and commit queue is really loooooong. Tomorrow I will come with more details in separate ticket.

**Comment by alessiodm** [comment]
@artembilan well at this point we are discussing about a non-existent feature, I agree it doesn't make much sense :)

Just as a personal feedback, I would really like to see such a feature implemented in `spring-kafka`. Especially because sometimes having an `at-most-once` semantic is useful, and Kafka allows that. I don't see any way to obtain it with `spring-kafka` at the moment, but please if you have any suggestion I would be very happy to hear.

Thanks again.

**Comment by artembilan** [comment]
Actually my Kafka knowledges are very superficial. I will be appreciate if you share some resource to understand what you are talking about in face of that `at-most(least)-once`. Feels like you would like to see something like record processing in the consumer thread directly, but I'm not sure in the point...

Thanks for feedback!

**Comment by alessiodm** [comment]
@artembilan you can find the definitions of the delivery semantics [here](http://kafka.apache.org/documentation.html#semantics) in the official Kafka documentation. They are very well-explained.

The last paragraph in particular mentions how Kafka enables the `at-least-once` semantic by default, and the `at-most-once` committing the offsets before processing the data.

Let me know if I can help in any other way. Thank you!

**Comment by martindam** [comment]
The at-most-once delivery is something that is supported by Kafka as @alessiodm pointed out. It is true that it not the most efficient way to use Kafka but for some applications the at-most-once semantics is needed. In my current scenario, I can accept loosing a message, but never process it twice which is why I need this semantics.

Reg. using a filtering adaptor: It is possible but in order to survive a crash or similar, we would have to store some state in an external system (e.g. Redis) to keep track of the offsets. At this point we are basically doing the same job as Kafka offset management offers us. 

We control the input topics and the properties of the producers. For this particular case, there is no duplicate messages in the topics so having the at-most-once semantics on the consumer would definitely fit our need. 

I would like to "insist", or rather, request, that you add this feature. It is a feature Kafka supports, but if I want to use the spring-kafka library I do not have that option. If this feature is not available I would have to write my own listener directly on the KafkaConsumer. However, that means I have to handle flow control, rebalance and proper testing of it, so I would much prefer making this small enhancement to this library which already provide 98% of my needs. 
If you want this functionality, let me know and I will submit a PR with it.

**Comment by mbogoevici** [comment]
One quick question: One way to achieve at most once is by setting auto offset commit at the consumer level, bypassing the ack mode, which Sprink Kafka currently supports. Is that something that would help in your case?

**Comment by martindam** [comment]
@mbogoevici I considered that, but that will not help in the case where the consumer is behind. In that case, it would receive a big batch of records and the consumer would mark all of them as being delivered, however the processing logic never had a change to see the messages. It would technically fulfill the requirements, but it opens up for loosing hundreds, even thousands of records at a crash. With the approach I propose I would loose at most one at a crash per consumer instance.

**Comment by mbogoevici** [comment]
@martindam that is true, but the batch (and subsequently the amount of data at risk) can be reduced by adjusting `max.partition.fetch.bytes`. YMMV on that one if message size is variable, but wondering how much complexity we should build into the framework as opposed to deferring to application tuning - which is especially true in 0.10, which supports `max.poll.records` as well. Anyway, thanks for the suggestion, it's worth weighing the two alternatives IMO.

**Comment by garyrussell** [comment]
@martindam 

>If you want this functionality, let me know and I will submit a PR with it.

Sorry - I was offline during this discussion and it has just been brought to my attention (thanks @artembilan !).

I concur this would be a useful addition so we'd be happy to see a PR - we would like to release a milestone for 1.1.0 soon and follow up with a GA release ASAP (to give people access to the 0.10.x.x client) .

It would be awesome if we could get this into the milestone.

Please note that `MANUAL_IMMEDIATE_SYNC` was removed (in favor of `MANUAL_IMMEDIATE` with sync/async being controlled by the container property `commitSync`).

We could reintroduce it, or simply always make manual commits "sync" from the listener's perspective if `commitSync` is true.

**Comment by fsantagostinobietti** [comment]
I'm missing this functionality too. 
Both solutions proposed by @garyrussell would be fine. To be honest my expectation was that MANUAL_IMMEDIATE with commitSync==true already did the magic. Probably I missed something in documentation.

Anyway, in my use case this is a very useful functionality.

**Comment by fcntl** [comment]
> FilteringAcknowledgingMessageListenerAdapter 

Randomly walk into a Java project on github. Already want to suicide.

**Comment by artembilan** [comment]
WDYT here about introduced recently transactions support: http://docs.spring.io/spring-kafka/docs/2.0.0.M3/reference/html/_reference.html#transactions?

May we consider this issue as fixed?

Thanks

**Comment by garyrussell** [comment]
I believe this is all moot since 1.3 and KIP-62; there are no longer 2 threads and MANUAL_IMMEDIATE commits are done on the calling thread (as long as it's the consumer thread).
