### ISSUE TITLE
Single Consumer for topic with multiple partitions not reading messages

### ISSUE THREAD

**Issue by shivam2146** [spring-projects/spring-kafka#1567]
**Affects Version(s):** 2.3.5.RELEASE

When I try to read messages from a few partitions it reads messages. The KafkaListener annotation is configured as:

`@KafkaListener(topicPartitions = @TopicPartition(topic = "topicName", partitions = {"0","1","2","3","4","5"}))`

But when I just put the topic name as param for KafkaListener annotation I keep on receiving the following messages
`{"message":"Received: 0 records","timestamp":1597581010242,"log.level":"DEBUG","logger.name":"org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer","thread.name":"org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1"}`

KafkaListener annotation in this case looks like:
`@KafkaListener(topics = "${spring.kafka.consumer.topics}")`
spring.kafka.consumer.topics property exists and has same topic name as in above case

Total number of partitions in my topic: 50
I am seeing the log for partition assigned and can see the correct offset corresponding to the consumer in KafDrop
I am running it on my local and there is only one consumer in consumer group with concurrency set as 1

**Comment by garyrussell** [comment]
GitHub issues are for reporting bugs and asking for new features. They are NOT for asking questions about why something is not working as you expect. Ask questions on Stack Overflow. Dis you read the instructions?

>🙅 "Please DO NOT Raise an Issue" Cases
>- Question
>STOP!! Please ask questions about how to use something, or to understand why something isn't
working as you expect it to, on Stack Overflow using the spring-kafka tag.

When using group management, you must set the `auto.offset.reset` property to `earliest` for a new group to receive existing records (its default is `latest`.

You also must use a different group.id (or delete the group using `kafka-consumer-groups.sh`) since the first listener would already have committed the offset of the last record it read.

**Comment by shivam2146** [comment]
I guessed missed the instruction. My bad. Will post it on stackoverflow. 
Anyways I have set `auto.offset.reset` to earliest and I tried with different groupid and still getting the same issue

**Comment by garyrussell** [comment]
What you are suggesting makes no sense; show code, configuration and logs in your SO question.

**Comment by shivam2146** [comment]
sure.
