### ISSUE TITLE
Move ContainerTestUtils to spring-kafka-test?

### ISSUE THREAD

**Issue by markward-schubert** [spring-projects/spring-kafka#157]
Would it be possible and wise to move the class ContainerTestUtils to the spring-kafka-test project? It appears, that the waitFor... methods could be useful in tests of projects, using spring-kafka. As the class is test-scoped in spring-kafka, it is not available int the using project though.

We were having some strange behavior with flakyness in our system-tests due to some assign / revoke condition. After a friendly hint from Artem Bilan, we managed to circumvent the issue, with code, close to the one in the aforementioned utils-class.

**Comment by garyrussell** [comment]
Unfortunately, no, we can't move it there because it would create a circular dependency between the two projects (`spring-kafka` already depends on `spring-kafka-test` and this would add the reverse dependency.

Although I am not a fan of this, one option would be for us to move it to a `...test` package under src/main. I don't think it's worth creating a whole new jar for just this class.

**Comment by artembilan** [comment]
Eh... What is sad that we even mention that class in the `testing.adoc`:
```
container.setBeanName("templateTests");
container.start();
ContainerTestUtils.waitForAssignment(container, embeddedKafka.getPartitionsPerTopic());
```
I'd say that we definitely should move it to `spring-kafka-test` and overcome explicit imports with reflection. Anyway it is for testing so won't hurt to have some hacks there.

**Comment by garyrussell** [comment]
Ah - good point; yes, we can use reflection.
