### ISSUE TITLE
Add possibility to configure StatefulRetry and ErrorHandler via applicaion.properties(yml)

### ISSUE THREAD

**Issue by lazystone** [spring-projects/spring-kafka#1594]
**Affects Version(s): <=2.6.1

🎁 Enhancement

In many our projects the only reason to have `@Configuration` for spring-kafka is to configure `StatefulRetry`+`SeekToCurrentErrorHandler`. And despite quite good documentation it's not always obvious how to do that properly(for example need of `ConcurrentKafkaListenerContainerFactoryConfigurer` is not that obvious).

It would be super-convenient to be able configure `StatefulRetry` and `ErrorHandler` via `application.properties` and have zero-code configuration for spring-kafka.

Example config might look something like
```
spring.kafka.listener.stateful-retry=true
spring.kafka.listener.error-handler=foo.bar.MyErrorhandler
```

**Comment by garyrussell** [comment]
`application.properties` are processed by Spring Boot's auto configuration; such requests should be made over on that project, not here.

That said, here are a couple of observations:

1. Stateful retry is pretty much obsolete since we added the capability to add a `BackOff` to the `SeekToCurrentErrorHandler`. https://docs.spring.io/spring-kafka/docs/2.6.1/reference/html/#stateful-retry

>Now that the SeekToCurrentErrorHandler can be configured with a `BackOff` and has the ability to retry only certain exceptions (since version 2.3), the use of stateful retry, via the listener adapter retry configuration, is no longer necessary. You can provide the same functionality with appropriate configuration of the error handler and remove all retry configuration from the listener adapter.

2. Error handlers typically need more sophisticated initialization than simply instantiating a class. For this reason, Spring Boot will automatically detect an `ErrorHandler` `@Bean` and wire it into the container factory automatically. It is not practical to configure it via a property.
