### ISSUE TITLE
@RetryableTopic Delays Between Attempts Longer Than Expected

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#1716]
```java
@SpringBootApplication
public class Kgh920Application {


	private static final Logger LOG = LoggerFactory.getLogger(Kgh920Application.class);


	public static void main(String[] args) {
		SpringApplication.run(Kgh920Application.class, args);
	}

	@RetryableTopic(attempts = 5, backoff = @Backoff(delay = 1000, multiplier = 2.0), kafkaTemplate = "kafkaTemplate")
	@KafkaListener(groupId = "kgh920", topics = "kgh920", containerFactory = "kafkaListenerContainerFactory")
	public void listen(String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
		LOG.info(in + " from " + topic);
		throw new RuntimeException("test");
	}

	@DltHandler
	public void dlt(String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
		LOG.info(in + " from " + topic);
	}

}
```
```log
$ grep 'foo from' ../tmp/retry.log
2021-02-25 15:11:15.639  INFO 69371 --- [ntainer#0-0-C-1] com.example.demo.Kgh920Application       : foo from kgh920
2021-02-25 15:11:26.196  INFO 69371 --- [etry-1000-0-C-1] com.example.demo.Kgh920Application       : foo from kgh920-retry-1000
2021-02-25 15:11:36.709  INFO 69371 --- [etry-2000-0-C-1] com.example.demo.Kgh920Application       : foo from kgh920-retry-2000
2021-02-25 15:11:47.221  INFO 69371 --- [etry-4000-0-C-1] com.example.demo.Kgh920Application       : foo from kgh920-retry-4000
2021-02-25 15:12:02.739  INFO 69371 --- [etry-8000-0-C-1] com.example.demo.Kgh920Application       : foo from kgh920-retry-8000
2021-02-25 15:12:03.245  INFO 69371 --- [ner#6-dlt-0-C-1] com.example.demo.Kgh920Application       : foo from kgh920-dlt
```

+10s, +10s, +10s, +15s

Perhaps something to do with the default poll timeout of 5 seconds, possibly affecting resume latency.

cc/ @tomazfernandes

**Comment by garyrussell** [comment]
Yes, somewhat improved with

    spring.kafka.listener.poll-timeout=1s

**Comment by garyrussell** [comment]
We should, perhaps, consider waking the consumer when resuming from paused (not sure if that will cause problems elsewhere though); we should at least document the situation.

**Comment by tomazfernandes** [comment]
Well, for this one there are two factors in consideration, which are the listener poll timeout as you said and also the partitionIdleInterval, which determines the frequency in which we'll check to see if the partition should be resumed.

As all the backoff logic is handled by the consumer thread I don't see really how to call wakeup unless we're willing to have another thread handling it, which I think might be an overkill... Makes sense?

I think the move here would be to properly document that, so that if the users' expectations is to have a higher resolution in the delay times they should adjust those settings accordingly.

What do you think?

**Comment by garyrussell** [comment]
Yes; I think documenting it is enough; I will change the labels.

**Comment by tomazfernandes** [comment]
Hi @garyrussell, just a quick update on this. 

I analysed the current behavior in order to document it and I didn't really feel ok with that - too much imprecision all around - that makes my sleep quality decrease 😄

So I went for an enhancement, and I think I've came up a good one - I can get an under 100ms precision OOTB for pretty much all delays over 1000ms. Still some work to be done though, like adjusting / creating tests, formatting for the checkstyle and updating the docs.

I can share details on the problem / solution if you want - or you can wait for the PR - however you'd like.

I thought I'd have this done by now already but some other things came up; I hope I'll have it ready in time for your review for RC-1.

Thanks!

**Comment by garyrussell** [comment]
Hi @tomazfernandes - just the PR is fine; if you want you can start a PR and add [NOT READY FOR MERGE] to the title, if you want me to take an early look.
