### ISSUE TITLE
Could not start stream: ; nested exception is java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by jeesk** [spring-projects/spring-kafka#1755]
os : window 10

🐞 question 
hey guys ! when i use kafka-stream,kafka-clients of version 2.6.1 , the console  prints out : Could not start stream: ; nested exception is java.lang.UnsupportedOperationException.   the exception comes from line 115 of the class StateDirectory.  Actually ,my computer os is window 10 , not linux .  I'm not sure if that's a bug. please help me , thanks you !

**Comment by garyrussell** [comment]
This has nothing to do with Spring, it is a [bug in Kafka Streams on Windows](https://issues.apache.org/jira/browse/KAFKA-12190).

It is fixed in 2.6.2, but that's not released yet (should be soon, I believe).

In the meantime, you can either drop back to kafka-streams (and kafka-clients) 2.6.0 or upgrade to 2.7.0.

See [here](https://docs.spring.io/spring-kafka/docs/current/reference/html/#update-deps) for information about how to change kafka library dependencies. Everything must be the same version; especially if you are using the embedded broker for testing.
