### ISSUE TITLE
KafkaEmbedded before/ after are protected

### ISSUE THREAD

**Issue by srinivasvsk** [spring-projects/spring-kafka#192]
Trying write tests using KafkaEmbedded with spock, it appears there is no manual way to start the broker. Both before and after method are somehow marked protected.
It would be nice to have the flexibility to call those methods.

Thanks

**Comment by garyrussell** [comment]
Sure, we can make those public.

**Comment by artembilan** [comment]
@srinivasvsk , 

that's because they are `protected` in the super `ExternalResource` class. So, when you extend the class and override those methods they are in the same visibility as in `super`.

Not a problem to make the m `public`.
Feel free to contribute: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc!

Meanwhile I guess you can extend `KafkaEmbedded` class to your own with `public` modifiers for `before()/after()`.

**Comment by artembilan** [comment]
Late. @garyrussell has done that already :smile:

**Comment by srinivasvsk** [comment]
Perfect! thanks for the quick response
