### ISSUE TITLE
Concurrency on partitions 

### ISSUE THREAD

**Issue by srinivasvsk** [spring-projects/spring-kafka#202]
Hello
IS there a way to achieve concurrency on the number of partitions using ConcurrentMessageListenerContainer, without having to use a predefined list of partitions in the Annotation code. Can concurrency be achieved after the KafkaConsumer gets assigned a list of partitions after its init?  That way rebalancing could scale up or down without having to configure partitions for each instance during application startup.

Thanks

**Comment by artembilan** [comment]
It isn't possible, because *assignment* is done by Kafka to the *Consumer*. Since we have received partitions by rebalance for one consumer, we can't assign any of them to another.

Right now we can have balanced, concurrent ListenerContainers by the `concurrency` option. And it is Kafka magic how each of them will be supplied for partitions from provided topics.

Please, elaborate more how that should work?

Thanks

**Comment by srinivasvsk** [comment]
Yeah, was guessing it didnt support but wanted to make sure.
So this is the thought, once you have an instance of the consumer, you look up the number of partitions this consumer got, something like consumer.partitionsFor(kafkaTopic). Then launch a thread for each partition and eventually you would process records from those threads as if @KafkaListener with single partition would do.  And somehow listen to the ConsumerRebalanceListener events and tear down those partition threads or add more.  
This would benefit a lot as more instances come or go from the consumergroup.
Kafka-streams ,i think calls it StreamThread but it may be creating a new instance of the consumer for each thread. 

Thanks for looking

**Comment by artembilan** [comment]
> Then launch a thread for each partition and eventually you would process records from those threads

I understand your idea about `consumer.partitionsFor(kafkaTopic)`, but that isn't good one at all.

When I developed AWS Kinesis Message Driven Channel Adapter, I realized that we can have `Maximum value of 100000.` of shards per stream. I guess similar number of partitions we may have in Kafka topic.

That's why such an approach "thread per partition" is really bad by the Java nature.
Therefore we can only have some pre-configured `concurrency` to distribute work to some reasonable amount of threads, not tens of thousands, of course.

Any other thoughts ?

**Comment by srinivasvsk** [comment]
Good point.  The approach i thought assumed the number of partitions are limited not like have a million partitions.
The problem with pre-configured concurrency, is failover has to be implemented by applications if we loose an instance with pre-configured partitions, there has to be a backup.
Thanks

**Comment by garyrussell** [comment]
I am not sure what your issue is.

If you use `topics` or `topicPattern` (instead of `topicPartitions`), the broker will assign the partitions automatically.

If you set the concurrency to, say, 3, and there are 10 partitions, they will be assigned across those 3 consumers; most likely 2 will get 3 each and the third will get 4; it's all done by the broker so the number of partitions is not known by the container.

The `topicPartitions` attribute is available for people who want to manually assign partitions.

**Comment by srinivasvsk** [comment]
I was looking through the code ConcurrentMessageListenerContainer, and below comments, i thought the only way to get concurrency was is to have the partitions defined, 

* Creates 1 or more {@link KafkaMessageListenerContainer}s based on
 * {@link #setConcurrency(int) concurrency}. If the
 * {@link ContainerProperties} is configured with {@link TopicPartition}s,
 * the {@link TopicPartition}s are distributed evenly across the
 * instances.

**Comment by garyrussell** [comment]
I think you misinterpreted the code.

	for (int i = 0; i < this.concurrency; i++) {
		KafkaMessageListenerContainer<K, V> container;
		if (topicPartitions == null) {
			container = new KafkaMessageListenerContainer<>(this.consumerFactory, containerProperties);
		}
		else {
			container = new KafkaMessageListenerContainer<>(this.consumerFactory, containerProperties,
					partitionSubset(containerProperties, i));
		}
                ...
    }

In the first branch of the `if` we start `concurrency` containers, each with all configured topics; Kafka takes care of distributing the topic partitions across the consumers, the container has no configuration relating to how many partitions there are. In the `else` branch we pass a subset of the configured partitions to each instance - distributing the partitions.

**Comment by srinivasvsk** [comment]
I'm glad its misinterpretation.  Thanks for including a great feature

**Comment by artembilan** [comment]
Great!
Can we consider the issue as closed?

Thank you for pointing that out anyway. 
In such a discussion the truth is born. :smile:

**Comment by srinivasvsk** [comment]
sure again thanks for your time !

**Comment by kevinconaway** [comment]
@artembilan I'd like to revisit this 

Topic partitions are the unit of consumer parallelism in Kafka.  It is common in many stream processing systems to have one thread per partition (see Apache Storm) provided that the number of partitions is relatively low and that they are scaled out across a number of consumer instances.

It would be very helpful to at least have the option to specify that you want to dynamically add a thread per partition when they are assigned to the consumer instance.  If you know that your topic has a number of partitions that would be unreasonable to run per thread inside a given consumer instance you could then cap them with the existing _concurrency level_ support

> When I developed AWS Kinesis Message Driven Channel Adapter, I realized that we can have Maximum value of 100000. of shards per stream. I guess similar number of partitions we may have in Kafka topic.

Its my understanding that it is currently inadvisable to have that many number of partitions (or even a 10th of that, https://www.confluent.io/blog/how-to-choose-the-number-of-topicspartitions-in-a-kafka-cluster/) but I don't have a lot of hard data to back that up.

**Comment by garyrussell** [comment]
@kevinconaway We could probably support a thread-per-partition (as long as you are using container commits or manual commit and not using auto-commit - which requires that the listener runs directly on the consumer thread which is "owned" by the kafka client, so it has to process all the assigned partitions).

However, it would add quite  bit of complexity to (what is already) fairly complex code. For example, when we detect a slow consumer on just one partition, we'd have to pause just that partition. Right now, if a listener is slow we pause all assigned partitions until the listener catches up. If you don't pause, then kafka will rebalance the partitions across other consumers. I am sure there would be other complexities too.

So, feel free to open a new issue, but I don't think we'll be able to apply any resources to it any time soon; contributions are always welcome, of course.

**Comment by artembilan** [comment]
It still isn't clear why existing `ConcurrentMessageListenerContainer` doesn't fit your requirements.
If your topic has 10 partitions, so start a container with 10 concurrency and each partition will have its own consumer thread according natural Kafka distribution: `consumer.subscribe(Arrays.asList(this.containerProperties.getTopics()), rebalanceListener);`. If you have re-partition at runtime, so stop the container and adjust its concurrency according a new partition count.

**Comment by kevinconaway** [comment]
Thanks for responding!

We generally make our consumer instances highly available for both fault tolerance and performance resasons.  This means that we'll have N number of consumer instances running on different machines.  

Doing so makes it difficult to predict how many partitions will be assigned to a given consumer instance without manually coordinating it.

**Comment by artembilan** [comment]
That's correct. That is how Apache Kafka partition assignment works:

```
 /**
     * Subscribe to the given list of topics to get dynamically
     * assigned partitions. <b>Topic subscriptions are not incremental. This list will replace the current
     * assignment (if there is one).</b> Note that it is not possible to combine topic subscription with group management
     * with manual partition assignment through {@link #assign(Collection)}.
     *
     * If the given list of topics is empty, it is treated the same as {@link #unsubscribe()}.
     *
     * <p>
     * As part of group management, the consumer will keep track of the list of consumers that belong to a particular
     * group and will trigger a rebalance operation if one of the following events trigger -
     * <ul>
     * <li>Number of partitions change for any of the subscribed list of topics
     * <li>Topic is created or deleted
     * <li>An existing member of the consumer group dies
     * <li>A new member is added to an existing consumer group via the join API
     * </ul>
     * <p>
     * When any of these events are triggered, the provided listener will be invoked first to indicate that
     * the consumer's assignment has been revoked, and then again when the new assignment has been received.
     * Note that this listener will immediately override any listener set in a previous call to subscribe.
     * It is guaranteed, however, that the partitions revoked/assigned through this interface are from topics
     * subscribed in this call. See {@link ConsumerRebalanceListener} for more details.
     *
     * @param topics The list of topics to subscribe to
     * @param listener Non-null listener instance to get notifications on partition assignment/revocation for the
     *                 subscribed topics
     * @throws IllegalArgumentException If topics is null or contains null or empty elements
     */
    @Override
    public void subscribe(Collection<String> topics, ConsumerRebalanceListener listener) {
```

**Comment by kevinconaway** [comment]
Yep so with that in mind, my request is similar to what was asked for here: https://github.com/spring-projects/spring-kafka/issues/202#issuecomment-259449751

If I have a topic with 20 partitions and run 4 instances of my application, each instance would get assigned 4 partitions.  I would like the option to have spring-kafka start up 4 threads for each partition so that they may be processed independently.

If one of my consumer instances crashes, Kafka will rebalance the partitions so that the 3 remaining instances get 7, 7 and 6 partitions respectively.  In that event, it would be good if spring-kafka spun up 7 (or 6) threads to handle the partition assignment.

The existing _concurrency level_ cap could come in to play so that I could set a maximum concurrency level (or max number of threads to use).  If a topic has 100 partitions, it would probably be detrimental to run 100 threads in a single instance.

Does that make sense?

**Comment by garyrussell** [comment]
It makes sense but, as I said, it would add a lot of complexity.

One work-around is to over-provision the consumers (i.e. provision 7 on each instance); the threads that don't get a partition won't use much in the way of resources; especially with a longer pollTimeout.

**Comment by garyrussell** [comment]
If you don't mind some "extra" rebalancing activity, it would probably not be too hard to detect when a consumer is allocated 2 (or more) partitions and start a completely new consumer in that case. It would cause another rebalance but things should settle down reasonably quickly. 

But we'd also need logic to stop some consumer(s) if no partitions are assigned after some period of time. 

I am just not keen on having the kafka consumer thread dispatching messages to individual listener threads and having to deal with pause/resume on some subset of partitions allocated to a consumer.

**Comment by kevinconaway** [comment]
> and having to deal with pause/resume on some subset of partitions allocated to a consumer.

I read through the spring-kafka documentation and I didn't really see any documentation on pausing/resuming.  I did see some mention of this in the code though.

Do you mind giving a short overview of what this is?

Kafka itself already has the notion of dealing with slow consumers (via the `max.poll.interval` in K10)

**Comment by garyrussell** [comment]
It looks like that might improve things. This code was originally written for the 0.9 client. See `zookeeper.session.timeout.ms` which defaults to 6 seconds.

> ZooKeeper session timeout. If the consumer fails to heartbeat to ZooKeeper for this period of time it is considered dead and a rebalance will occur.

So, to handle slow consumers we added pause/resume support so that we keep talking to kafka until the listener catches up.

See `ContainerProperties.setPauseEnabled`.

I sounds like the 0.10 client now has a better mechanism so perhaps this is no longer necessary, which would simplify the container greatly.

**Comment by kevinconaway** [comment]
> It looks like that might improve things. This code was originally written for the 0.9 client. See zookeeper.session.timeout.ms which defaults to 6 seconds.

Isn't that for the old scala client code?  Based on my review of the code, I thought that you are using "new" `KafkaConsumer` which handles timeouts differently (via `heartbeat.interval.ms`).

In K9, the heartbeat timeout is 30 seconds and is tightly coupled to `poll()`.  So if you take longer than 30s before calling `poll()` again, it will force a rebalance.

These two KIPs explain the problem better than I can and how it was addressed in K10:

https://cwiki.apache.org/confluence/display/KAFKA/KIP-41%3A+KafkaConsumer+Max+Records
https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread

**Comment by garyrussell** [comment]
Yes; you're right; sorry. It was the 30 second timer with a large message-fetch that caused us to implement the pause/resume.

It looks like the ability to use a separate thread for heartbeats (and the max.records settting) will enable the container simplification.

**Comment by garyrussell** [comment]
Time to ramp-up a 1.2.x release, I guess 😄
