### ISSUE TITLE
Consider Allowing the Same Container Factory for Retryable and Normal @KafkaListener

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#2069]
See https://stackoverflow.com/questions/70701185/infinite-loop-when-using-retryabletopic/70701460#70701460

**Comment by garyrussell** [comment]
The `ListenerContainerFactoryConfigurer` unconditionally uses a customizer to `setupBackoffAwareMessageListenerAdapter()`.

cc/ @tomazfernandes Thoughts?

**Comment by tomazfernandes** [comment]
Well, seems like an useful and interesting challenge - from the top of my head I can't really see a simple solution for this... The factory that will create the retryable topics' containers needs to have both the customizer and the error handler with the DLPR, and the factory that will create the non retryable topics' container can't have either.

Maybe we could add some conditional logic to the customizer so it'd skip certain containers. The error handler should be trickier though.

Did you think of something? I can look deeper into it next week if you'd like, or feel free to do so if you prefer.

Also, maybe we can see a way to at least throw an error if the user does this, so they won't get stuck in the loop not knowing what's happening.

**Comment by garyrussell** [comment]
Thanks; I hadn't thought it through but, yes, I guess we could have some kind of marker on the container that can be tested in the customizer.

No rush; that's why I put it on the backlog; we should look to see if we can fail fast, though.

**Comment by tomazfernandes** [comment]
Hi, I think I found a way to make this work. 

Instead of setting the properties directly to the factory, I created a wrapper for the factory that is returned by the `ListenerContainerFactoryConfigurer` instead of the provided instance. The wrapper sets the necessary properties directly to the container in the `createContainer` methods, so nothing is changed in the factory instance itself, and nothing is changed for non retryable topics.

The problem I see with this solution is that the `ListenerContainerFactoryConfigurer` public API (the `configure` and `configureWithoutBackOffValues` methods) relies specifically on the `ConcurrentKafkaListenerContainerFactory` class, instead of the `KafkaListenerContainerFactory` interface, as it should.

So instead of a clean wrapper implementing the interface, I had to subclass the `ConcurrentKafkaListenerContainerFactory ` class, and then it gets messier to guarantee all public method calls will be made to the delegate instead of the wrapper's instance superclass.

Maybe it's not that much of an issue - let me know what you think. I'll try to think of a way around this without breaking the contract. If you have any ideas please let me know.

I pushed a POC of this solution to my repo, in case you want to take a look or try it out. It has a test `RetryTopicSameContainerFactoryIntegrationTests` that fails as intended, since it checks for the infinite loop (30 retries on the non-retriable topic that should be retried only 10 times). If you remove my changes it passes, indicating the infinite loop the user mentioned.

The basic integration tests pass normally - I didn't run all the tests since there are a few unit tests that'd have to be changed.

Thanks!

**Comment by garyrussell** [comment]
The approach looks reasonable, but I wonder if it would be simpler to add a boolean property to the container, then, in `doConfigure`, only call `setupBackoffAwareMessageListenerAdapter` if `container.isRetryable()`.

However, I noticed another problem there; we unconditionally set the container customizer - this might override a user-provided customizer.

We probably need to check for an existing customizer and make this customizer a composite - and call the existing customizer too.
