### ISSUE TITLE
Spring Kafka is not working with Spring 3.0.5.RELEASE

### ISSUE THREAD

**Issue by AbhinavRam123** [spring-projects/spring-kafka#207]
My project is already developed with Spring 3.0.5.RELEASE, We are planning to use Kafka for new requirements. I am trying to use spring-kafka (from 1.0.x to 1.1.x) but it is not supporting with Spring 3.0.5.RELEASE. Application is throwing "class not found  exception org.springframework.core.task.AsyncListenableTaskExecutor"

Please help me to move forward.

Thanks
Abhi

**Comment by artembilan** [comment]
To move forward you have to upgrade your project to Spring 4.1.x at least: http://docs.spring.io/spring-kafka/docs/1.1.1.RELEASE/reference/html/_introduction.html#compatibility.

Or use Apache Kafka directly. Although I'm not sure that it is compatible with Java 5 or even 6...

Otherwise there is no use of Spring Kafka for you

**Comment by AbhinavRam123** [comment]
Thanks Artem for the quick reply, No issues with JDK , My project is compatible with Java 7. Spring Kafka is providing so many features. My worry is, I am able to use Spring Kafka with Spring3.0.5

**Comment by artembilan** [comment]
That's correct: you can't use Spring Kafka with so old Spring version.
Since you are OK with Java 7, I don't see reason to stay with out-of-support Spring version and just move forward with all the upgrades!

Otherwise we are sorry and can't help you. We are not going to provide Spring Kafka version for EOL Java and Spring versions.

**Comment by AbhinavRam123** [comment]
Thanks Artem.
