### ISSUE TITLE
Very, Very Quick demo has a bug

### ISSUE THREAD

**Issue by q6413260** [spring-projects/spring-kafka#213]
the Very, Very Quick demo has such code:
1 
```
ContainerProperties containerProps = new ContainerProperties("topic1", "topic2");
KafkaMessageListenerContainer<Integer, String> container = createContainer(containerProps);
final CountDownLatch latch = new CountDownLatch(4);
```
2 
```
containerProps.setMessageListener(new MessageListener<Integer, String>() {
        @Override
        public void onMessage(ConsumerRecord<Integer, String> message) {
            logger.info("received: " + message);
            latch.countDown();
        }
});
```
i think we should  `containerProps.setMessageListener(xxx)` first,
then `ContainerProperties containerProps = new ContainerProperties("topic1", "topic2");`
if not `container.start()` will throw an exception 

> org.springframework.kafka.listener.KafkaDataListener implementation must be provided

**Comment by artembilan** [comment]
Yes, that's correct: `KafkaListenerContainer` cannot be started without listener.

I guess you mention a sample in the [Reference Manual](http://docs.spring.io/spring-kafka/docs/1.1.1.RELEASE/reference/html/_introduction.html#_very_very_quick):

````java
 ContainerProperties containerProps = new ContainerProperties("topic1", "topic2");
    KafkaMessageListenerContainer<Integer, String> container = createContainer(containerProps);
    final CountDownLatch latch = new CountDownLatch(4);
    containerProps.setMessageListener(new MessageListener<Integer, String>() {

        @Override
        public void onMessage(ConsumerRecord<Integer, String> message) {
            logger.info("received: " + message);
            latch.countDown();
        }

    });
    container.setBeanName("testAuto");
    container.start();
````
After the fix for https://github.com/spring-projects/spring-kafka/issues/154 we now **copy** the `ContainerProperties` internally in the `AbstractMessageListenerContainer`:
```
if (containerProperties.getTopics() != null) {
			this.containerProperties = new ContainerProperties(containerProperties.getTopics());
		}
		else if (containerProperties.getTopicPattern() != null) {
			this.containerProperties = new ContainerProperties(containerProperties.getTopicPattern());
		}
		else {
			this.containerProperties = new ContainerProperties(containerProperties.getTopicPartitions());
		}

		BeanUtils.copyProperties(containerProperties, this.containerProperties,
				"topics", "topicPartitions", "topicPattern", "ackCount", "ackTime");
```
So, yes, it is definitely bug and its fix like move ` containerProps.setMessageListener()` before the ` createContainer(containerProps)`.

Another fix can be like `AbstractMessageListenerContainer.setupMessageListener()` before calling its `start()`.

The reference manual will be fixed soon.

**Comment by q6413260** [comment]
yes，i  ran the Very, Very Quick demo in the Reference Manua。
thanks to answer the question
