### ISSUE TITLE
Multiple @RetryableTopic on the same topic

### ISSUE THREAD

**Issue by loonis** [spring-projects/spring-kafka#2282]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?** : 2.8.6

I have 2 listeners (2 groupIds) : service-1 & service-2 listening  the same topics : `myTopic`

When service-1 fails, I expect the message to be pushed in the retry queue : `myTopic-service_1_retry-0`
Similarly, when service-2 fails, I expect the message to be pushed in the retry queue : `myTopic-service_2_retry-0`

Here is an example of my listeners.

```java
@Service
@Slf4j
@RequiredArgsConstructor
public class MyListeners {

  @RetryableTopic(
      attempts = "2",
      numPartitions = "9",
      kafkaTemplate = "kafkaTemplate1",
      backoff = @Backoff(delay = 30000),
      topicSuffixingStrategy = TopicSuffixingStrategy.SUFFIX_WITH_INDEX_VALUE,
      retryTopicSuffix = "-service_1_retry",
      listenerContainerFactory = "kafkaListenerContainerFactory1",
      dltTopicSuffix = "-service_1_dlt")
  @KafkaListener(
      containerFactory = "kafkaListenerContainerFactor1",
      groupId = "service-1",
      concurrency = "9",
      topics = "myTopic",
      errorHandler = "logExceptionErrorHandler")
  public void processMessageService1(ConsumerRecord<String, Event> message) {
      throw new IllegalStateException("test");
  }

  @RetryableTopic(
      attempts = "2",
      kafkaTemplate = "kafkaTemplate2",
      numPartitions = "9",
      backoff = @Backoff(delay= 30000),
      topicSuffixingStrategy = TopicSuffixingStrategy.SUFFIX_WITH_INDEX_VALUE,
      retryTopicSuffix = "-service_2_retry",
      listenerContainerFactory = "kafkaListenerContainerFactory2",
      dltTopicSuffix = "-service_2_dlt")
  @KafkaListener(
      containerFactory = "kafkaListenerContainerFactory2",
      groupId = "service-2",
      concurrency = "9",
      topics = "myTopic",
      errorHandler = "logExceptionErrorHandler")
  public void processMessageService2(ConsumerRecord<String, Event> message) {
    return;
  }

}
```

When I push a message in the `myTopic` topic and it fails for service-**1**, the message is being pushed in the myTopic-service_**2**_retry-0, which is not what I expect.

For more details, here is the KafkaConfig file I use
```java

@EnableKafka
@Configuration
@Slf4j
public class KafkaConfigExample {

  @Autowired
  private ConsumerFactory<String, Event> consumerFactory;

  @PostConstruct
  public void updateDefaultConfiguratiion() {
    JsonDeserializer<Event> jsonEventDeserializer = new JsonDeserializer<>(Event.class);
    jsonEventDeserializer.setRemoveTypeHeaders(false);
    jsonEventDeserializer.addTrustedPackages("*");
    jsonEventDeserializer.setUseTypeMapperForKey(true);
    ((DefaultKafkaConsumerFactory) consumerFactory).setValueDeserializer(new ErrorHandlingDeserializer<>(jsonEventDeserializer));
  }

  @Bean
  KafkaListenerErrorHandler logExceptionErrorHandler() {
    return (Message<?> msg, ListenerExecutionFailedException ex) -> {
      if(ex.getCause().getClass().equals(InputException.class)){
        log.warn("Unable to process message: {} with error: {}",msg, ex);
      } else {
        log.error("Unable to process message: {} with error: {}",msg, ex);
      }
      throw ex;

    };
  }

  @Bean
  public KafkaTemplate<String, Event> kafkaTemplate1(ProducerFactory<String, Event> producerFactory) {
    return new KafkaTemplate<>(producerFactory);
  }

  @Bean
  public KafkaTemplate<String, Event> kafkaTemplate2(ProducerFactory<String, Event> producerFactory) {
    return new KafkaTemplate<>(producerFactory);
  }

  @Bean
  public ConcurrentKafkaListenerContainerFactory<String, Event> kafkaListenerContainerFactory1(ConsumerFactory<String, Event> consumerFactory) {
    ConcurrentKafkaListenerContainerFactory<String, Event> factory = new ConcurrentKafkaListenerContainerFactory<>();
    factory.setConsumerFactory(consumerFactory);
    return factory;
  }

  @Bean
  public KafkaTemplate<String, Command> kafkaTemplateCommand(ProducerFactory<String, Command> producerFactory) {
    return new KafkaTemplate<>(producerFactory);
  }

  @Bean
  public ConcurrentKafkaListenerContainerFactory<String, Event> kafkaListenerContainerFactory2(ConsumerFactory<String, Event> consumerFactory) {
    ConcurrentKafkaListenerContainerFactory<String, Event> factory = new ConcurrentKafkaListenerContainerFactory<>();
    factory.setConsumerFactory(consumerFactory);
    return factory;
  }


}
```

**Comment by tomazfernandes** [comment]
Sure @artembilan! 

The problem is that we currently use `topic` as key in the `DestinationTopicResolver` singleton - since both containers have the same topic, one entry overwrites the other.

https://github.com/spring-projects/spring-kafka/blob/93f5ae5c7cc65e9ebf1b2e310fdeb106bb04ed51/spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopicResolver.java#L42

If we're interested in solving this for 2.x, the simplest fix I can think of would be enriching the key perhaps with the `containerId`.

Here is where we populate the `Map` that contains the destinations:
https://github.com/spring-projects/spring-kafka/blob/93f5ae5c7cc65e9ebf1b2e310fdeb106bb04ed51/spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicResolver.java#L194-L201

Here is where we retrieve it:
https://github.com/spring-projects/spring-kafka/blob/93f5ae5c7cc65e9ebf1b2e310fdeb106bb04ed51/spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java#L202-L203

We should probably also look into having the framework create a separate set of topics for each container by default so that the user wouldn't need to specify different suffixes for that.

For 3.0, if we end up doing that refactoring where each `DLPR` gets a `DestinationTopicResolver`  instance and a `Registry` bean, maybe that new key wouldn't be necessary - each resolver would have its own chain of retry topics for the main topic. It'd probably be a good idea to have the automatic creation / usage of different retry topics for each topic though.

**Comment by lukasz-dronka** [comment]
Yeah, this one effectively stops us in my project from using multiple consumer groups with retries for each of them. Would be wonderful to get this sorted out!

**Comment by tomazfernandes** [comment]
Hi @pieterPurple, sorry, I don’t think I’ll be able to work on this for 3.0. Perhaps @garyrussell can take a look, or feel free to provide a PR if you’d like.

**Comment by garyrussell** [comment]
Sorry, this was not on my radar. The 3.0 release candidate is due tomorrow so this won’t make that. However, for another reason I have scheduled RC2 in a couple of weeks so we can try to get this into that.

**Comment by garyrussell** [comment]
Turns out we already had a test with two listeners on the same topic but, it didn't check the topic names; I have enhanced it to do so (and it fails, as expected). 

https://github.com/garyrussell/spring-kafka/commit/9feab545ad7dd0ae33981ef8a562899e0b365c9a

Just need to figure out the simplest way to fix it.

One possibility is to make `DefaultDestinationTopicResolver.sourceDestinationsHolderMap` a map of maps, keyed by listener id.

**Comment by tomazfernandes** [comment]
Sounds great @garyrussell, thanks for looking into this!

Yeah, that test was to assert annotations on separate listeners within the same consumer group but for different manually assigned partitions.

The map of maps sounds great. Not sure if anything needs to be adjusted on the setup side besides the map population, but as you mentioned the test should be conclusive on that.

It's a good thing this is for 3.0 since probably a few interfaces will need to adapt to receiving the listener id, and this way I guess we don't need to keep the old methods.

Thanks!

**Comment by garyrussell** [comment]
PR issued.

**Comment by hpruszyn** [comment]
Is it possible to introduce this fix to the 2.* release? Or maybe some workaround can fix this issue in Spring Boot 2?

**Comment by garyrussell** [comment]
@hpruszyn The changes are too extensive to consider for a back-port at this time.

However, you should be able to work around it by using an entirely custom topic naming strategy.

See the documentation: https://docs.spring.io/spring-kafka/docs/2.9.10/reference/html/#custom-naming-strategies

**Comment by garyrussell** [comment]
@hpruszyn The changes are too extensive to consider for a back-port at this time.

<strike>However, you should be able to work around it by using an entirely custom topic naming strategy.</strike>

See the documentation: https://docs.spring.io/spring-kafka/docs/2.9.10/reference/html/#custom-naming-strategies

Correction; I don't have a work around at this time.

**Comment by garyrussell** [comment]
Actually, you should be able to work around it by loading the second listener in its own `ApplicationContext`.
