### ISSUE TITLE
Using receive-and-reply mechanism in an async way

### ISSUE THREAD

**Issue by marov83** [spring-projects/spring-kafka#2325]
**Expected Behavior**

It woud be usefull to Receive-n-reply mechanizm work with Future<> or Mono<>

**Current Behavior**

Receive-n-reply mechanizm throws exception

**Context**
I use ReactiveMongoRepository and Spring WebClient and I need something like this work without block.

    @SendTo
    @KafkaListener(topics = "some")
    public Future<String> getBatchInfo(String batchCode){...}

**Comment by artembilan** [comment]
Related SO thread: https://stackoverflow.com/q/72829959/2756547

**Comment by garyrussell** [comment]
We could model it after the `@RabbitListener` support. https://docs.spring.io/spring-amqp/docs/current/reference/html/#async-returns

However, it's more tricky with Kafka because there is no concept of acknowledging discrete messages; the container would have to be configured to support out of order commits; with the added risk of duplicate deliveries.

**Comment by Wzy19930507** [comment]
Hi, @sobychacko This issue repeat with #1189 , we can close it.

**Comment by artembilan** [comment]
Closed as `Duplicated` of #1189
