### ISSUE TITLE
Seeking to a specific offset using ConcurrentMessageListenerContainer with ConsumerSeekAware 

### ISSUE THREAD

**Issue by maxceban** [spring-projects/spring-kafka#246]
I've been trying to implement a feature in my application that would allow to invoke a custom seek during runtime.
I've implemented the `ConsumerSeekAware` in my listener class and registered the callback instances per partition upon assignment, but I'm having issues invoking the seek operation.
It looks like kafka's consumer is pretty defensive with regards to which threads are allowed to access it simultaneously. 
As per the documentation, the only details regarding the threads is: `you should store the callback in a ThreadLocal or some other structure keyed by the listener Thread.`
It looks to me that the issue is that the implementation of the `ConsumerSeekCallback` invokes the seek operation directly on the kafka consumer instances instead of the seek on the ListenerConsumer instances:
```java
ConsumerSeekCallback callback = new ConsumerSeekCallback() {

	@Override
	public void seek(String topic, int partition, long offset) {
		ListenerConsumer.this.consumer.seek(new TopicPartition(topic, partition), offset);
	}
};
```
https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L461

Since ListenerConsumer internally implements a consumer loop, I don't understand how is it possible to call the kafka consumer without causing thread conflicts. 
According to the implementation, it looks like `ListenerConsumer` has a way of invoking the seek via the seeks `LinkedBlockingQueue` that gets polled within the consumer loop.

**Comment by garyrussell** [comment]
@maxceban That particular callback (in `seekPartitions`) is only ever called on the consumer thread. The callback passed into `onPartitionsAssigned()` and `onIdleContainer()` __must only be used in the scope of those method calls__ - which guarantees the seek is performed on the consumer thread. The callback passed in via `registerSeekCallback()` is the one you can save off (in  a `ThreadLocal<?>`) for later, arbitrary, seeks.

When `autoCommit` is true, the listener is (and has to be) invoked on the actual consumer thread. Otherwise, the listener is invoked on the listener thread.

In either case, the `SeekCallback` that is registered with the listener (via `registerSeekCallback()`) is the `ListenerConsumer` object and it's `seek()` method always queues the seek requests so they run on the kafka consumer thread (as is required, as you point out).

The reason we suggest storing the callback in a thread local is for multi-threaded listeners so the seek goes to the right consumer.

This complexity (extra thread) was required because in 0.9.x and 0.10.0, the kafka client tied heartbeats to polls and thus a slow listener would cause a rebalance. We detect slow listeners and pause/resume the consumer as needed.

Thankfully, the 0.10.1 client now handles heartbeats separately [KIP-62](https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread).

We therefore plan on always running the listener on the consumer thread in the next release, to remove this complexity.

Please let us know if you still feel there's a problem here.

**Comment by garyrussell** [comment]
Closing with no response; please reopen if you feel there is still an issue.
