### ISSUE TITLE
suggestion: change @RetryableTopic replicationFactor default to -1 (broker default)

### ISSUE THREAD

**Issue by benissimo** [spring-projects/spring-kafka#2471]
Currently the default value is "1".
That's fine when developing against docker, but in most real world situations the brokers will have min.insync.replicas set to some higher value, obliging the developer to override.
If instead the default value were "-1", that means use whatever the broker's default replication factor is.
This saves the developer from having to think about replication factor unless they need something different.

**Comment by garyrussell** [comment]
Out of curiosity, how did you create an issue with no labels? The `New Issue` button asks you to select between a bug and a new feature.

We can change this default in 3.0; we can't really do it in earlier releases because this is not valid if the broker is < 2.4.

We made a similar change in spring-cloud-stream.

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1202#issuecomment-1050204443

**Comment by benissimo** [comment]
Thanks for adding the label. I submitted the ticket via https://github.com/spring-projects/spring-kafka/issues/new and didn't see a prompt to choose how to categorize it.

I hadn't realized replicas = -1 would only work with Kafka as of 2.4. Good point! It would be useful in 3.0.0 though. Thanks for adding it to the milestone.

**Comment by garyrussell** [comment]
Ah - thanks; yes the "New Issue" button opens https://github.com/spring-projects/spring-kafka/issues/new/choose
