### ISSUE TITLE
Kafka Clients dependency not upgraded

### ISSUE THREAD

**Issue by poduvalmanu3** [spring-projects/spring-kafka#2625]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.0.4

**Describe the bug**

In the maven page you can see that there has been an upgrade to the kafka clients but the same is not refelcted in the pom file hence it still uses the older dependency which has a security vulnerability. Can you please take a look at this
**To Reproduce**

Build with spring-kafka version 3.0.4
**Expected behavior**

The kafkaClients library should be upgraded to version 3.4

**Screenshots**
![image](https://user-images.githubusercontent.com/12817461/225601032-a87f7e4c-b33e-4351-86aa-aa2aae0f2c1c.png)

**Comment by garyrussell** [comment]
Spring projects cannot upgrade to a new major or minor version of dependencies in a patch release; we can only upgrade to a new patch release of the dependency; e.g. `3.3.2->3.3.3`.

Supported versions https://spring.io/projects/spring-kafka#support are fully compatible with the 3.4.0 clients; you just have to override the dependency in your application; see https://docs.spring.io/spring-kafka/docs/current/reference/html/#update-deps for how to do that in a Spring Boot app; if not using Boot, just override the dependency version.

The CVE fixed in 3.4.0 is in Kafka Connect, which is not used by this project; it is only an issue if you use this project and connect in the same application.

**Comment by garyrussell** [comment]
The next version (3.1, currently planned, but likely later this year) will use the latest clients available at that time.

**Comment by garyrussell** [comment]
The next version (3.1, currently **not** planned, but likely later this year) will use the latest clients available at that time.

**Comment by poduvalmanu3** [comment]
Thank you for the update
