### ISSUE TITLE
Snyk vulnerablility - Apache-kafka-client < v3.5 

### ISSUE THREAD

**Issue by criticalerror-rf** [spring-projects/spring-kafka#2735]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.0.8

**Describe the bug**

Snyk will detect issues with Spring-kafka v 3.0.8 because it uses apache-kafka-client v3.4.1 which has serious vulerabilities

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

Snyk delta analysis will reveal that the apache-kafka-client has vulnerabilities 
```
[2023-07-11T11:15:57.069Z] New issue introduced !

[2023-07-11T11:15:57.069Z] Security Vulnerability:

[2023-07-11T11:15:57.069Z] 

[2023-07-11T11:15:57.069Z]   1/1: Denial of Service (DoS) [High Severity]

[2023-07-11T11:15:57.069Z]     Via: org.apache.kafka:kafka-clients@3.4.1 => org.xerial.snappy:snappy-java@1.1.8.4

[2023-07-11T11:15:57.069Z]     Fixed in: org.xerial.snappy:snappy-java 1.1.10.1
```

**Comment by artembilan** [comment]
Our support policy doesn't allow us to upgrade to minor versions in our point version.
If Apache Kafka provides the fix into their `3.3.x`, then we gladly upgrade our current version.
Otherwise this will wait until we start our `3.1` version.

You simply can override Apache Kafka client version in your project to mitigate discrepancy: https://docs.spring.io/spring-kafka/docs/current/reference/html/#update-deps.

Spring Boot `3.2` will come with Apache Kafka `3.5` though: https://github.com/spring-projects/spring-boot/issues/35954

Closed as `Won't Fix` according to the explanation above.
