### ISSUE TITLE
No early bean initialization from `EmbeddedKafkaContextCustomizer`

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#2870]
See https://github.com/spring-projects/spring-framework/issues/31453#issuecomment-1787252754

While we don't support the embedded broker in native images; the problem seems to be that the broker is not shut down properly.

**Comment by snicoll** [comment]
The problem is rather that the broker is starting "manually" as part of a callback that should not start any bean, see 

https://github.com/spring-projects/spring-kafka/blob/0dfde15edf4b66706fc411137c1ec624e0064d4b/spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizer.java#L127-L128


> Customize the supplied ConfigurableApplicationContext after bean definitions have been loaded into the context but before the context has been refreshed.

I think it should rather contribute a `RootBeanDefinition`. Unfortunately, the contract of this method is a bit strange as it should provide a registry, not a  context since it has not been refreshed yet.

Here is an example in Spring Boot of what I mean: https://github.com/spring-projects/spring-boot/blob/8f2ec227389391fdd173db0ab64f26abd2752f20/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/web/client/TestRestTemplateContextCustomizer.java#L62

**Comment by artembilan** [comment]
Just debugged one of the test using `@EmbeddedKafka`. The `EmbeddedKafkaZKBroker.destroy()` is called and all the brokers and Zookeeper are shouted down in normal JVM.
I fail to find that `@DisabledInAotMode` to mark our `@EmbeddedKafka`, but I see that mentioned `TestRestTemplateContextCustomizer` uses `if (AotDetector.useGeneratedArtifacts()) {`.
Maybe that would be enough for us as well.
At the same time I don't see too much difference with what we have so far with a `((DefaultSingletonBeanRegistry) beanFactory).registerDisposableBean(EmbeddedKafkaBroker.BEAN_NAME, embeddedKafkaBroker);` and what Spring Boot does:
```
	if (beanFactory instanceof BeanDefinitionRegistry registry) {
			registerTestRestTemplate(registry);
		}
```

Even if we are about migrating to the `RootBeanDefinition`, we still need a `BeanDefinitionRegistry` registry.
So, I don't understand what we are pursuing here.

Thanks

**Comment by snicoll** [comment]
Again, this isn't a problem with shutdown. It's not even a problem with AOT actually even if it surfaces only when one tries to process the test context using Spring AOT.

>  I don't see too much difference with what we have [...] and what Spring Boot does

There's a huge difference. Spring Kafka creates a singleton an force start it at a time where only the context can be customized before the refresh (see javadoc). Spring Boot registers a bean definition that's going to be handled just like any other bean at the appropriate time.

> Even if we are about migrating to the RootBeanDefinition, we still need a BeanDefinitionRegistry registry.

Correct and there's nothing in the issue I can see that's asking that. I've tried to explain that with "Unfortunately, the contract of this method is a bit strange as it should provide a registry, not a context since it has not been refreshed yet.".

**Comment by artembilan** [comment]
Still not clear why is that harmful.
The `EmbeddedKafkaBroker` instance does not have any dependencies, therefore that `beanFactory.initializeBean(embeddedKafkaBroker, EmbeddedKafkaBroker.BEAN_NAME);` is thing by itself just to call its `afterPropertiesSet()` to start embedded brokers before the real test suite.
And therefore changing it to the:
```
((BeanDefinitionRegistry) beanFactory).registerBeanDefinition(EmbeddedKafkaBroker.BEAN_NAME, 
				new RootBeanDefinition(EmbeddedKafkaBroker.class, () -> embeddedKafkaBroker));
```
won't have too much difference for the end result.
(Assuming that we agreed we don't need to rework it to plain `BeanDefinition` configuration since no AOT support for this type of tests.)

**Comment by garyrussell** [comment]
The difference is `initializeBean()` creates the broker immediately, whereas registering a bean definition defers the creation until the context is refreshed.
