### ISSUE TITLE
EmbeddedKafkaKraftBroker.kafkaPorts(int... ports) is ignored

### ISSUE THREAD

**Issue by zyro23** [spring-projects/spring-kafka#2916]
First of all, thanks for the new `EmbeddedKafkaBroker` abstraction and the KRaft impl.!

**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.1.0

**Describe the bug**

`EmbeddedKafkaKraftBroker.kafkaPorts(int... ports)` sets the `kafkaPorts` array but it seems that is never used?

ref.: https://github.com/spring-projects/spring-kafka/blob/v3.1.0/spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaKraftBroker.java#L148-L160

**To Reproduce**

```java
EmbeddedKafkaKraftBroker broker = new EmbeddedKafkaKraftBroker(1,1)
    .kafkaPorts(9092);
```
-> still uses random port.

**Expected behavior**

The `EmbeddedKafkaKraftBroker` actually uses the specified port(s).

**Sample**

ping me if you think a sample is helpful here.

**Comment by sobychacko** [comment]
@zyro23 Currently, it is not possible to propagate custom ports in `KafkaClusterTestKit`. We just documented this via javadocs.

**Comment by sobychacko** [comment]
I asked the broader Apache Kafka community this question [here](https://stackoverflow.com/questions/77588470/configure-ports-using-kafkaclustertestkit). If we have an update, we can revisit this issue and open it again.

**Comment by garyrussell** [comment]
For the record, it is not good practice to hard code the port used in tests. It can cause conflicts when multiple test run concurrently on the same machine.

**Comment by zyro23** [comment]
> For the record, it is not good practice to hard code the port used in tests. It can cause conflicts when multiple test run concurrently on the same machine.

fully agreed - as far as tests are concerned (happy with `EmbeddedKafkaKraftBroker` & random port(s)).

however, we are also using `EmbeddedKafkaZKBroker` with static/configured ports at runtime for local development (providing an embedded alternative to an external/containerized broker).
would be great to be able to use `EmbeddedKafkaKraftBroker` for that scenario, too :)

**Comment by sp193** [comment]
If we aren't recommended to hardcode the port, how can we get the broker address for Kafka client configuration when not using the default Spring Boot Kafka configuration classes? I have my own configuration classes to configure Kafka, as we may retrieve the Kafka settings and secrets from 3rd party services.

There seems to be a spring.embedded.kafka.brokers property and I assume it gets set at some point, but it does not seem to get set when it is needed. I guess that it's not getting set in time, due to my configuration class getting instantiated before the embedded broker is configured. But I cannot find a way to get this configuration in time, without making spring-kafka-test a dependency.

I am trying to keep the test dependencies out of the release builds. Could you please advise me on how I can elegantly achieve such a thing?

**Comment by artembilan** [comment]
@sp193 ,

Sounds like a `Discussion`.
Please, consider to raise a new one with much more info.
You question is really not relevant to this issue and perhaps would have some other solution.
Thanks
