### ISSUE TITLE
Topic exists exception thrown when using EmbeddedKafkaRule

### ISSUE THREAD

**Issue by bernie-schelberg-invicara** [spring-projects/spring-kafka#3023]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.0.4. Issue was discovered in 2.2.15.RELEASE, but verified present in 3.0.4.

**Describe the bug**

Sometimes topics created in an earlier test are still present in later tests, even though a new EmbeddedZookeeperServer is created. This causes an exception to be thrown when the `EmbeddedKafkaRule` calls `afterPropertiesSet()` on the `EmbeddedKafkaBroker` (when the `EmbeddedKafkaBroker` calls `createTopics()`). I'm not sure if the issue is in this project, or in Kafka itself, but I'm starting here. I spent a considerable amount of time debugging but have been unable to identify the root cause of the problem. A new Zookeeper server is started for each test, and should have clean log and snapshot directories, but somehow, sometimes it doesn't.

**To Reproduce**
[embedded-kafka-rule-test.zip](https://github.com/spring-projects/spring-kafka/files/14218196/embedded-kafka-rule-test.zip)
I've attached a zip file containing a small project reproducing the issue. Note that it doesn't occur 100% of the time. If it consistently works for you, try increasing the `LOAD_FACTOR` constant in `AbstractEmbeddedKafkaRuleTest`. Increasing the number of topics / messages appears to more reliably reproduce the issue. Naturally, it may appear contrived, but I started seeing this issue with only 2 topics, and 1 or 2 message in each topic. It failed about 20% of the time on my machine.

**Expected behavior**

Tests should not fail with "topic already exists" errors.

**Sample**
[Minimal reproducible sample](https://github.com/bernie-schelberg-invicara/embedded-kafka-rule-test)

**Comment by artembilan** [comment]
Yes. You test is very hard to reproduce just because you use that `"test-topic-" + UUID.randomUUID()`.
Also I don't see how `EmbeddedKafkaBroker.afterPropertiesSet()` can fail if you start it without any topics upfront: `new EmbeddedKafkaRule(1, true, 1)`.
I also think, even if you have that `public static EmbeddedKafkaRule embeddedKafka` in the abstract class, every single extension of that class would get its own `EmbeddedKafkaRule` instance.
So, if you believe that two of those `EmbeddedZookeeperServer` looks into the same target Kafka dir, then it is indeed the problem in the Kafka Client test library or even downstream in the `java.nio.file.TempFileHelper`.

Please, consider to make your test as reliably reproducible as possible to give us a chance to dig more what is going on.

Also consider to try to upgrade to the latest Spring for Apache Kafka: perhaps some fixes has made it into any of transitive dependencies.

**Comment by bernie-schelberg-invicara** [comment]
@artembilan I generate random topics for every test. This is the practice recommended here: https://stackoverflow.com/a/60064493/1303158. The test prints out all the topic name it creates, so you can see that when it fails, the "topic exists" error that is thrown by the second test is a topic that is created for the first test.
I also don't see how `EmbeddedKafkaBroker.afterPropertiesSet()` can fail without any topics upfront, however that is the behaviour that my demo exhibits. As I said, more load increases the likelihood of failure, so I suspect that there's some kind of race condition - I speculate that some asynchronous operation called by `EmbeddedKafkaBroker.destroy()` does not have enough time to complete, and so some element of Kafka or Zookeeper carries over into the next test run.
Using `public static EmbeddedKafkaRule embeddedKafka` means there is only one instance of the `EmbeddedKafkaRule` no matter how many subclasses are instantiated. The static field is on the abstract superclass, not on each one of the subclasses.
...
I spent some more time investigating and discovered that a `KafkaProducer` was still running after the test completes, it appears as though this is the root cause of the issue. So finally I realised that I must call either `ProducerFactory.reset()` or `DefaultKafkaProducerFactory.destroy()` after I'm finished with the `KafkaTemplate`. My tests are now working as expected.
I'm closing this issue as there's nothing really to fix.
