### ISSUE TITLE
Spring Kafka not working properly with Java 21 Virtual Threads, listeners are tied to a platform thread forever

### ISSUE THREAD

**Issue by Moscagus** [spring-projects/spring-kafka#3074]
[jstack.txt](https://github.com/spring-projects/spring-kafka/files/14411614/jstack.txt)
[jcmd.txt](https://github.com/spring-projects/spring-kafka/files/14411615/jcmd.txt)
Spring Boot 3.2.3

Virtual Kafka listeners are tied to a platform thread forever.

The problem I see is that validating with jcmd and jstack the listeners are tied to a platform thread forever. 
Therefore it does not make effective use of virtual threads.
Without messages in Kafka and with a concurrency of 20, I have 20 platform threads carrying the virtual threads.

I have 3 cores. Therefore I have to have only 3 ForkJoinPool-1-worker platform threads waiting.
But in reality I have 3 waiting and another 20 carrying the listeners.

[oracle@vtuerto kafka-2602]$ cat jstack.txt | grep -A 1 ForkJoinPool-1-worker | grep WAITING
   java.lang.Thread.State: TIMED_WAITING (parking)
   java.lang.Thread.State: WAITING (parking)
   java.lang.Thread.State: WAITING (parking)
[oracle@vtuerto kafka-2602]$ cat jstack.txt | grep -A 1 ForkJoinPool-1-worker | grep Carrying
   Carrying virtual thread #38
   Carrying virtual thread #73
   Carrying virtual thread #47
   Carrying virtual thread #76
   Carrying virtual thread #80
   Carrying virtual thread #61
   Carrying virtual thread #43
   Carrying virtual thread #92
   Carrying virtual thread #45
   Carrying virtual thread #64
   Carrying virtual thread #84
   Carrying virtual thread #88
   Carrying virtual thread #69
   Carrying virtual thread #96
   Carrying virtual thread #100
   Carrying virtual thread #104
   Carrying virtual thread #108
   Carrying virtual thread #112
   Carrying virtual thread #116
   Carrying virtual thread #51

**Comment by artembilan** [comment]
Any chances to confirm that this kind of dead-lock is indeed caused by Spring for Apache Kafka?
How about to make something similar based on virtual threads, but just with plain Apache Kafka client?
See more info in the similar issue: https://github.com/spring-projects/spring-kafka/issues/3013

The virtual threads is totally Java feature, not Spring, so making them working, the whole call stack should follow specific recommendation.
The `synchronized` block is one of those which causes virtual threads to be pinned to platform one.

Thanks for understanding!

**Comment by Moscagus** [comment]
When checking the stacks in "jcmd.txt", I found a place where the Apache Kafka client due to a "synchronized" causes virtual thread to be pinned to plataform one. 
It is the heartbeat thread for each spring kafka listener (concurrency).
I give as an example one:

           "tid": "51",
           "name": "kafka-coordinator-heartbeat-thread | Group_topic_1",
           "stack": [
              "java.base\/jdk.internal.misc.Unsafe.park(Native Method)",
              "java.base\/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)",
              "java.base\/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754)",
              "java.base\/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:990)",
              "java.base\/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)",
              "java.base\/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)",
              "org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:264)",
              "org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:321)",
              "org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1460)"
           ]


Looking at the code on github for "AbstractCoordinator$HeartbeatThread.run" you can clearly see the synchornized.
https://github.com/apache/kafka/blob/3.6/clients/src/main/java/org/apache/kafka/clients/consumer/internals/AbstractCoordinator.java#L1443

        @Override
        public void run() {
            try {
                log.debug("Heartbeat thread started");
                while (true) {
                    synchronized (AbstractCoordinator.this) {

It would be good if you can contact the Kafka people about this issue, otherwise it doesn't make any sense that the documentation says that Spring for Apache Kafka supports virtual threads.

**Comment by artembilan** [comment]
Thank you for the report!
Yes, we will try to find some contact with Apache community.

Would you mind to do the same via their public channels?

**Comment by artembilan** [comment]
Well, there is not too much we can do.
Looks like Kafka client creates those unconditionally:
```
    private synchronized void startHeartbeatThreadIfNeeded() {
        if (heartbeatThread == null) {
            heartbeatThread = new HeartbeatThread();
            heartbeatThread.start();
        }
    }
```
Which really are not configurable to be virtual. 

This one is called from the stack of the `KafkaConsumer.poll()`.
So, yeah: every single `KafkaConsumer` instance creates that `HeartbeatThread` for itself.
The Kafka client needs to look into making that one as virtual.

For now it is apparent that concurrency for Kafka listener must not be more than platform threads.
Or even a bit less since we still need to have some threads to run those `KafkaConsumer.poll()` calls...

**Comment by sobychacko** [comment]
I created an issue in the Apache Kafka jira backlog to track this: https://issues.apache.org/jira/browse/KAFKA-16309. Thanks!

**Comment by Moscagus** [comment]
exactly as you mention:
https://github.com/apache/kafka/blob/3.6/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L734
the problem begins

Thanks

**Comment by Moscagus** [comment]
I continued investigating and in the end the problem is not in the Kafka consumer. 
The Kafka Consumer uses the Java core "sun.nio.ch.SelectorImpl". This class uses "synchronized".
Rather than opening a case against Apache Kafka, we have to wait for a future version of Java to resolve "synchronized".

https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/sun/nio/ch/SelectorImpl.java#L123

Until this is resolved, Spring Kafka should not enable by default "SimpleAsyncTaskExecutor" as its "ListenerTaskExecutor"

**Comment by artembilan** [comment]
Well. It is still can be enabled by default, just the concurrency must not exceed the number of platform threads.
Is there a ticket in JDK we can follow about that `SelectorImpl`?

**Comment by Moscagus** [comment]
Although it does not seem correct to me to use a feature when it has such a clear limitation, at the very least you would have to document this limit

**Comment by sobychacko** [comment]
We can certainly document it. In addition, I don't think it is entirely a JDK issue; as @artembilan pointed out earlier in the comments, Kafka consumer also creates the `HeartbeatThread` in a `synchronized` block. So that needs to be addressed for sure.  Also, did you verify if there is a corresponding JDK issue for addressing the `SelectorImpl` issue?

**Comment by Moscagus** [comment]
The problem is definitely not the "HeartbeatThread".
Did @sobychacko see the jcmd.txt I sent ?
If you haven't seen it, please watch it.

Just in case, I'll copy a piece of it anyway:

           "tid": "64",
           "name": "Kafka-Listener-7",
           "stack": [
              "java.base\/sun.nio.ch.EPoll.wait(Native Method)",
              "java.base\/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:121)",
              "java.base\/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)",
              "java.base\/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:142)",
              "org.apache.kafka.common.network.Selector.select(Selector.java:874)",
              "org.apache.kafka.common.network.Selector.poll(Selector.java:465)",
              "org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:571)",
              "org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)",
              "org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:251)",
              "org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1255)",
              "org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1186)",
              "org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1159)",
              "org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollConsumer(KafkaMessageListenerContainer.java:1659)",
              "org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doPoll(KafkaMessageListenerContainer.java:1634)",
              "org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1432)",
              "org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1323)",
              "java.base\/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)",
              "java.base\/java.lang.VirtualThread.run(VirtualThread.java:309)"
           ]

**Comment by sobychacko** [comment]
I meant that although the heartbeat thread may not be the issue here, it could still cause some race conditions in other situations; therefore, I think the Kafka issue we created is still valid (at least to verify). I am surprised, though, that the `SelectorImpl` virtual thread issue hasn't come up for other scenarios since that is used by many other libraries; that's why we were curious if there is a corresponding JDK issue filed for that.

**Comment by artembilan** [comment]
I think that `SelectorImpl` is just a consequence of blocked platform threads where most of them are those `HeartbeatThread` from Kafka Client.
And these are created for every single `KafkaConsumer` instance in your application. Therefore making a concurrency as `300` would lead into `300` of `HeartbeatThread` instances.

**Comment by artembilan** [comment]
Here is a set of libraries which uses same `Selector.select()` API (at least from Spring Integration dependencies):
```
< temurin-17 >
java.nio.channels
jdk.internal.net.http
sun.net.httpserver
com.hazelcast:hazelcast:5.3.6
com.rabbitmq:amqp-client:5.19.0
io.netty:netty-transport:4.1.107.Final
org.apache.kafka:kafka-clients:3.7.0
org.apache.mina:mina-core:2.1.6
org.apache.qpid:proton-j:0.34.1
org.apache.tomcat.embed:tomcat-embed-core:10.1.19
org.apache.zookeeper:zookeeper:3.8.4
org.igniterealtime.smack:smack-core:4.5.0-alpha2
org.mongodb:mongodb-driver-core:5.0.0
org.zeromq:jeromq:0.6.0
```

So, how that turned out to be a problem if it is so fundamental feature of many async libraries?

**Comment by Moscagus** [comment]
You clearly don't understand Project Loom well.

Take the trouble to prototype using libraries that end up using the event loop (select,poll) pattern and they will all misuse virtual threads because of this synchronized.
Netty, for example, still has an open case
https://github.com/netty/netty/issues/8439

No problem, we would continue talking and the truth is it doesn't make sense.
The important thing is that the Spring Kafka documentation mentions this limitation.

**Comment by artembilan** [comment]
Being rude is not helpful in Open Source community.
Blocking you: https://docs.github.com/en/site-policy/github-terms/github-community-guidelines

**Comment by Moscagus** [comment]
> Here is a set of libraries which uses same `Selector.select()` API (at least from Spring Integration dependencies):
> 
> ```
> < temurin-17 >
> java.nio.channels
> jdk.internal.net.http
> sun.net.httpserver
> com.hazelcast:hazelcast:5.3.6
> com.rabbitmq:amqp-client:5.19.0
> io.netty:netty-transport:4.1.107.Final
> org.apache.kafka:kafka-clients:3.7.0
> org.apache.mina:mina-core:2.1.6
> org.apache.qpid:proton-j:0.34.1
> org.apache.tomcat.embed:tomcat-embed-core:10.1.19
> org.apache.zookeeper:zookeeper:3.8.4
> org.igniterealtime.smack:smack-core:4.5.0-alpha2
> org.mongodb:mongodb-driver-core:5.0.0
> org.zeromq:jeromq:0.6.0
> ```
> 
> So, how that turned out to be a problem if it is so fundamental feature of many async libraries?

Do you consider this response kind?

**Comment by sobychacko** [comment]
We updated the documentation with the limitations of using virtual threads with the message listener containers. See this commit for more details: https://github.com/spring-projects/spring-kafka/commit/ae775d804f82483f99d4cab2a16ef2b27649252a. Thank you!

**Comment by samuelstein** [comment]
I got the problem during integration testing.
My solution was to switch to Spring Boot 3.2.5 and use concurrency=1

**Comment by danishnawab** [comment]
I have run into a similar issue despite being on JDK 24, which fixes the synchronization pinning issue: [JEP 491: Synchronize Virtual Threads without Pinning](https://openjdk.org/jeps/491).

The output from `jstack -l <pid>` and `jcmd <pid> Thread.dump_to_file -format=json threads.json` is attached. 
Can you please help me ascertain if this is caused by the same underlying issue? If so, I will report the issue to JDK, since the expectation was that the pinning issue (for synchronized) should go away now. 
If not, please also advise on how to proceed.

[jstack.txt](https://github.com/user-attachments/files/20390228/jstack.txt)
[threads.json](https://github.com/user-attachments/files/20390227/threads.json)

(I have anonymized the stack frames/thread names in case they showed the name of internal software)

This is a spring boot application with ~20 `@KafkaListener`s, some (not all) of which configure explicit concurrency setting, in the following way:

```java
@KafkaListener(topics = TOPIC, concurrency = "4", groupId = GROUP_ID)
```

The maximum value for concurrency in 4. `Runtime.getRuntime().availableProcessors()` on the server also returns 4. 

The Java version is as follows:
```
$ java -version
openjdk version "24.0.1" 2025-04-15
OpenJDK Runtime Environment Zulu24.30+11-CA (build 24.0.1+9)
OpenJDK 64-Bit Server VM Zulu24.30+11-CA (build 24.0.1+9, mixed mode, sharing)
```

**Comment by sobychacko** [comment]
@danishnawab Just making sure that you are not running into the issues mentioned here: https://docs.spring.io/spring-kafka/reference/4.0/kafka/thread-safety.html#_special_note_on_virtual_threads_and_concurrent_message_listener_containers.

Also, if this is really a new issue, please open a new GH issue as this issue has been closed for a long time. We might want to take a fresh look at this if there is indeed some issues.

**Comment by artembilan** [comment]
You application has too many threads, so that is hard to judge that Spring for Apache Kafka is involved some how.
You talk about `@KafkaListener` and its concurrency, but what is with Micrometer collector?
What about OK HTTP?
What is that `instana`?
I mean too many variable to extract anything from your huge files.

I'm not good with thread dumps, but I feel that it would be better to isolate Spring for Apache Kafka specific parts as much as possible to claim that we have a problem over here.

Thank you for understanding!

**Comment by danishnawab** [comment]
@sobychacko the warning is no longer relevant, because starting Java 24, the issue with synchronized block has been resolved, so this can't be it, unless there is a bug in the JDK, which is what I am trying to find out. 
PS. it would be a good idea to update the docs to include the hint about JDK 24.

@artembilan that's because this is a full application that ran into this issue. I don't have a way to reproduce it, it is inherently non-deterministic. If it helps, I can trim the thread dumps to remove the non-kafka threads, but that would just be artificial, since I have no way of isolating the problem. I posted here to see if someone could spot the issue as-is, but if that's not possible I of course understand that it's not an easy task to sift through so many stack traces.

**Comment by danishnawab** [comment]
@artembilan here is the JEP: https://openjdk.org/jeps/491 (release: 24)

**Comment by JanKanis** [comment]
> Right. I saw that link in your previous comment. That looks for me like ticket in bug tracker. That is not an official fix and its documentation. I don't think we can point to JEP from our documentation. Plus, as you said, this is from Java 24. We cannot push everyone so high. More over, even our upcoming Spring Framework 7 generation is going to stay on Java 17.

It's also listed in the JDK 24 release notes: https://www.oracle.com/java/technologies/javase/24-relnote-issues.html#491
