### ISSUE TITLE
Request to consider providing default ApplicationListener to stop the SpringBoot Kafka Consumer application on container failures

### ISSUE THREAD

**Issue by LokeshAlamuri** [spring-projects/spring-kafka#3329]
**Application Type:** Spring Boot Kafka Consumer application to poll the data from the Kafka and log the message.

**Scenario:** Spring Kafka Consumer application Message Listener container stopped due to some internal error. 

**Problem:** Application still running even though Kafka Consumer Listener Container stopped. No useful work is done from this point.

**Solution:** Stop the Application on receiving KafkaContainerStopped notification. I have done some draft work in this regard. Kindly review the following link and give your suggestions.

https://github.com/LokeshAlamuri/SpringBootKafkaConsumerDemo/blob/main/src/main/java/com/example/springboot/ConsumerStoppedEventListener.java

**Comment by artembilan** [comment]
This scenario is not standard since not all application are supposed to be fully stopped just because one of its listener container is stopped for some reason.
It is fully OK to have such a custom logic in the target project, but that is not what we would consider having as an out-of-the-box feature.

Please, elaborate more why this event listener with `applicationContext.close();` has to become the framework component?
Plus keep in mind that this is a core library and has nothing to do with Spring Boot.

**Comment by LokeshAlamuri** [comment]
I agree that Spring Boot is not related to this issue. Since, Spring Boot is the most common choice I have taken Spring Boot in to this discussion. Apologies.
I am also not proposing to stop **the application by default** when the Spring Kafka Message Listener Container fails. 
I have done some draft work to stop the application on Container failure. It may not be 100% correct. But, it is a good idea to provide an utility for this use case to stop/close the application context on Spring Kafka Message Listener Container failures. This would release the application resources and will help in graceful shutdown. It would be the spring user choice to whether to use this utility or not. There are many such utilities being provided with Spring targeting different projects. There are multiple projects where the use case is to poll the messages from Kafka, process and store them in DB and send some further events. Please give your suggestions.

**Comment by LokeshAlamuri** [comment]
> This scenario is not standard since not all application are supposed to be fully stopped just because one of its listener container is stopped for some reason. It is fully OK to have such a custom logic in the target project, but that is not what we would consider having as an out-of-the-box feature.
> 
> Please, elaborate more why this event listener with `applicationContext.close();` has to become the framework component? Plus keep in mind that this is a core library and has nothing to do with Spring Boot.

**I agree that Spring Boot is not related to this issue.** Since, Spring Boot is the most common choice I have taken Spring Boot in to this discussion. Apologies.
I am also not proposing to stop **the application by default** when the Spring Kafka Message Listener Container fails. 
I have done some draft work to stop the application on Container failure. **It may not be 100% correct.** But, it is a good idea to provide an utility for this use case to stop/close the application context on Spring Kafka Message Listener Container failures. This would release the application resources and will help in graceful shutdown. **It would be the spring user choice to whether to use this utility or not.** There are many such utilities being provided with Spring targeting different projects. With in Spring-Kafka itself, multiple error handlers are provided targeting to different scenarios. Not, all of them are used in a single project. There are multiple projects where the use case is to poll the messages from Kafka, process and store them in DB and send some further events. Please give your suggestions.

**Comment by artembilan** [comment]
> There are many such utilities being provided with Spring targeting different projects. 

Would you mind pointing to those utilities?

Again: that your `ConsumerStoppedEventListener` is so simple that it does not justify to be a part of the framework.
Usually, the target application is not so simple with just Kafka listeners and simple hard decision to fully close the application when no active consumers any more.
I believer such an `ApplicationListener` abstraction in Spring Framework is powerful enough utility to do whatever we want in our application.
No further assumption is required from the framework perspective.

**Comment by LokeshAlamuri** [comment]
> > There are many such utilities being provided with Spring targeting different projects.
> 
> Would you mind pointing to those utilities?
> 

Please find one simple yet useful component in spring-kafka module.

**org.springframework.kafka.listener.CommonLoggingErrorHandler** -- This is a CommonErrorHandler implementation for logging exceptions. 

Even though it is simple, it is useful and handy for simple use cases where the user just wants to log the exceptions on error scenarios.  This error handler may not be used in every project.

There are many such components which could be simple but they are handy. These kind of components speeds up the application development.

> Again: that your `ConsumerStoppedEventListener` is so simple that it does not justify to be a part of the framework. Usually, the target application is not so simple with just Kafka listeners and simple hard decision to fully close the application when no active consumers any more. I believer such an `ApplicationListener` abstraction in Spring Framework is powerful enough utility to do whatever we want in our application. No further assumption is required from the framework perspective.

Let the project be simple or complext. In general (I am not saying that it should be like this only, but for sure majority cases) if at all a Message Listner Container is stopped, no useful processing would happen and there is no point in keeping the application alive. Every user would prefer to release the critical application resources in a proper way. In this case it would be beneficial for the users to provide handy solution by providing in the commons library or atleast we could mention it in the documentation about this scenario. 

	It could be simple but it is critical and worth providing the solution in this regard. I agree ApplicationListener abstraction in Spring Framework is powerful enough utility. It is an abstraction. This would require the user to explore what exactly it. Let us implement solution for this critical use-case or document on how to use this utility.

**Comment by artembilan** [comment]
The `CommonLoggingErrorHandler` is very light for the whole application and it is really idempotent. So, no comparing apples with apples.
What you suggest with that `ConsumerStoppedEventListener` is very heavy operation on the whole application.
That is your use-case to stop the application when no more active consumer.
What if other project are not that strict and their decision to stop an application might be much complicated?
Therefore they would need to implement their own `EventListener`.

And since the logic of your `ConsumerStoppedEventListener` is straightforward and pretty obvious in some scenarios and again too hard on the whole application, I don't want to include it into the framework to encourage people for some falsely assumption.
Plus, in general this project is a library and must not have any opinion on the target application behavior if that has nothing to do with Apache Kafka.

The documentation for the  `EventListener` is out this project scope anyway.

I'm not sure why you are so insisting on this feature since the goal of this project is interaction with Apache Kafka.
The application behavior is not that one and should be implemented somewhere else. 
Of course, in most cases in that application.

**Comment by sobychacko** [comment]
@LokeshAlamuri Thanks for the report. While I see the issue from an application perspective, I think these scenarios are better handled at the application level, as @artembilan suggested. We cannot simply shut down the entire application context based on the errors from the message listener. While this makes sense in your use case, some other applications don't want them to be stopped as they might be in the middle of some other processing (think about a monolithic app responsible for multiple processes). Shutting down the context prematurely might have other unknown side effects we can't control from the framework angle. Your solution looks great to me from the application side because it is tailored to your use case. Framework doesn't have that kind of visibility and make assumptions like that. Furthermore, if such a custom `EventListener` is available from the framework, there is the potential for misusing that component and running into unforeseen issues.

**Comment by LokeshAlamuri** [comment]
Thank you for your valuable comments. I am about to close this issue. I would request you to take a moment at the following summary and give your final comments. 

1) Issue I have reported is a standard and critical scenario for most of the microservice based applications. It is not just to my application. 

2) **Computing power is a costlier resource.** In general if at all a critical component like KafkaMessageListenerContainer has failed, no useful would be done from that point. Any one would prefer to stop the application to save their costs. Even from the operations perspective, It would give the wrong picture since the application is live but not doing any processing work. **I feel that this is not an assumption from the framework side.** Implementing or documenting the solution for this scenario doesn't give any false assumptions. User would include the components as per their requirements.

3) Please find the class **org.springframework.boot.SpringApplicationShutdownHook**. In this class, there is some functionality to close the ApplicationContext. If at all a user chooses to exit the Sytem, then this SpringApplicationShutdownHook is activated. This is enabled by default for all Spring Boot applications.

4) 'ConsumerStoppedEventListener' I have provided may not be a complete solution and may not be also correct. I provided that to reprot the problem or gap and the possible solution.

5) We are not closing ApplicationContext prematurily. We are closing it once Container has stopped and then releasing the resources using the standard approach.

6) I am insisting on this since it is critical. This is left undocumented and unimplemented. There is some gap in this regard.  

7) Please let me know how a custom EventListener from the framework could create a potential issues. **This is a user choice. Almost every one would prefer this.** We do have such component 'org.springframework.boot.SpringApplicationShutdownHook'. That does the similar task as I have proposed. It is enabled by default.

8) **I agree that these things could be better handled at the application side. But, I have seen many common, simple to complex components provided in the framework. For that reason only I have reported this issue and thought of having some official solution in this regard.**

**Comment by sobychacko** [comment]
@LokeshAlamuri We understand your concerns, but as mentioned above, this is a valid use case for your application. As such, you should be able to clean up any components that would cost computing resources as soon as possible in the application based on application-specific logic. The framework already provides facilities to achieve this, such as the shutdown hook you mentioned or your custom event listener. The implementation you provided has this logic:
```
if(listenerContainerRegistry.getListenerContainers().stream().
                filter(messageListenerContainer -> messageListenerContainer.isRunning()).count() == 0)
            applicationContext.close();
```
You are checking if the container is running or not. The way that flag becomes `false` in a normally running application is when the container is [stopped](https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L410). We already publish an event for capturing the container stopped event - https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/main/java/org/springframework/kafka/event/ContainerStoppedEvent.java.

Another option is to listen for this `ContainerStoppedEvent` and then stop the context or shut down the application based on that.

**Comment by LokeshAlamuri** [comment]
Thank you. Closing the issue as this use-case could be better handled from the Application side.
