### ISSUE TITLE
ConcurrentKafkaListenerContainerFactory to handle multiple RecordInterceptors

### ISSUE THREAD

**Issue by micd** [spring-projects/spring-kafka#3374]
Hi, while working with ConcurrentKafkaListenerContainerFactory and kafka interceptors we encountered a problem that with bean post processor setting an interceptor there is no possibility to check if there is any set and/or accumulate them. The only option is to override an interceptor and the last post processor wins. Eg. see https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/11793

There are multiple options eg. implementing a getter on `listenerContainerFactory` or to make `ConcurrentKafkaListenerContainerFactory` accumulate interceptors into composite interceptors eg. by changing behaviour of setter or adding `add` method that will do accumulation by using composite interceptor if the field is set.

Would that be possible? What do you think?

**Comment by artembilan** [comment]
There is a `CompositeRecordInterceptor` which is exactly for such a use-case.

You probably have to disable that `ConcurrentKafkaListenerContainerFactoryPostProcessor` and use its logic in your own  `CompositeRecordInterceptor` definition with your own interceptor to be injected into a `ConcurrentKafkaListenerContainerFactory`.

We may add a getter, but that sounds more reasonable that Otel would provide an API to use interceptor directly in the configuration instead of that non-reliable `ConcurrentKafkaListenerContainerFactoryPostProcessor`.

**Comment by micd** [comment]
> There is a CompositeRecordInterceptor which is exactly for such a use-case. 
yeah, it's just not used by `ConcurrentKafkaListenerContainerFactoryPostProcessor`, we can use it while setting, but if there is another component setting that the only option is to override the interceptor.

I think it's not only about otel, otel is just an exampe, it's about a general behaviour when having multiple sources trying to set the interceptor independently eg. kafka factory configuration, post processor or two-three-x different postprocessors we will end up with just one of them being eventually successful. 

If I could propose the solution I'd rather change behaviour of `set` or add/change it for `add` method with given behaviour:
* if interceptor is null set it
* if interceptor is not null take the current value and given one, wrap into composite interceptor and set

This would be a general solution which would solve these problems and also some of similar problems that other users had.

**Comment by artembilan** [comment]
We will discuss this internally with the team.
However I still feel that `BeanPostProcessor` is wrong direction to do that stuff.
It would be better to design a consumer of this library the way that it is compliant with an API suggestion by the library.
The `ConcurrentKafkaListenerContainerFactory` is a configuration phase component, therefore it can be modified only once as a bean definition or via its supporting configurers.
The design of its API follows Java Beans specification, therefore constructors and setters.
For use-cases like you describe we indeed have that `CompositeRecordInterceptor` which should be used when we need to inject several interceptors.

Also, play attention, we have support for Micrometer Observation which is compatible with Otel: https://docs.spring.io/spring-kafka/reference/appendix/micrometer.html

**Comment by micd** [comment]
> We will discuss this internally with the team.

Thanks! Could you please let me know the results?

**Comment by sobychacko** [comment]
@micd We had a team discussion on this issue. Here is what we generally agreed upon. As @artembilan alluded to above, it is an anti-pattern for third-party libraries to use a `BeanPostProcessor` to inject directly to `ConcurrentKafkaListenerContainerFactory` using a mutator method on the factory. There are a couple of reasons for this. One primary reason is the problem reported on this issue, i.e., multiple third-party libraries override the interceptor, and the last one who calls the mutator wins. Another reason is that you are letting the third-party library unconditionally set the interceptor on the factory. While it might be perfect for your use case, it is not unreasonable to think that other applications do not prefer to apply the interceptor on all `ConcurrentKafkaListenerContainerFactory` beans unconditionally. They might prefer to only apply the interceptor based on some conditions. Because of these reasons, we strongly recommend against third-party libraries calling setters like this on the `ConcurrentKafkaListenerContainerFactory.` A better design is to let them expose the interceptors as public APIs of their libraries, and you (the end-user application) dictate when and what interceptors to add to the factory. In other words, the end-user application knows best what to do with the application. We realize that making these changes in the external libraries is impractical since they are outside your control. Therefore, going with what Artem said is the best strategy here - i.e., disable this post-processor bean from your application and then copy the logic and use a `ComposeRecordInterceptor` or (the batch equivalent) to add the desired interceptors in your application. 

Another solution we considered was modifying the `ConcurrentKafkaListenerContainerFactory` so that it provides an `addInterceptor` method. While this is fairly easy to implement, there are some serious ramifications we need to consider. Imagine a future version of the framework in which this ` add` method is present, and multiple libraries use it to add the interceptor to the factory. What if two different libraries add an interceptor and try to add a new header with the same name? Clearly, one would override the other. Another consideration is the iteration order. The interceptors are added and called in the order in which they are called. What if one interceptor added by a library relies on the header added by another library, and the application calls these libraries in the wrong order? While it sounds like a contrived scenario, it is a plausible use case that could happen. 

Because of these factors, we are inclined not to make such changes in the framework. We highly recommend that end-user applications use the composite version of the interceptors, add the needed interceptors, and then call the setter on the factory. What do you think?

**Comment by micd** [comment]
hey @sobychacko solution and reasoning behind that that you've described sounds good and seems to be the best way to solve or avoid issues with interceptor. 

Thanks a lot. Appreciate your and your team's effort.
