### ISSUE TITLE
Wrong comparison of server bootstrap addresses in KafkaTemplate.afterSingletonsInstantiated

### ISSUE THREAD

**Issue by bleipold1** [spring-projects/spring-kafka#3466]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

3.2.3

**Describe the bug**

In line 490 of KafkaTemplate are the bootstrap server addresses of the producer factory and the bootstrap server addresses of the kafka admin bean compared  with each other. In most cases this will fail, because producerServers is a list of strings and adminServers always string. Even if the string represents the same list.

**To Reproduce**

**Expected behavior**

If producerServers and adminServers represent the same bootstrap servers, the if branch should not be entered.

**Comment by sobychacko** [comment]
@bleipold1 Thanks for the report. We will look into this soon.

**Comment by sobychacko** [comment]
@bleipold1 While it looks like an issue, we are curious how you encountered this issue. If they don't match (even by type), then we get into the conditional for creating a new `KafkaAdmin`. 

Also, this only happens if you have a Boot application because you always get the bootstrap server config from Boot as a `List`.
