### ISSUE TITLE
Lower the replication factor for transactions topic when using embedded Kafka broker for tests

### ISSUE THREAD

**Issue by dlyash** [spring-projects/spring-kafka#3557]
**Expected Behavior**

It would be nice if the embedded broker started by `@EmbeddedKafka` (or the similar JUnit Rule) defaulted the replication factor for the transaction state topic to the number of brokers, or a `min(<number-of-brokers>, 3)`. 

**Current Behavior**
The embedded broker starts with the default configuration of `transaction.state.log.replication.factor = 3` which doesn't make sense for a single-broker cluster, which is quite common in tests:
```
org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.
```

**Context**
It's not a big deal, as it can be resolved by explicitly setting broker properties like follows. But a meaningful default would save some time for thousands of developers googling the problem again and again.
```
@EmbeddedKafka(brokerProperties={
    "transaction.state.log.replication.factor=1"
})
```

**Comment by sobychacko** [comment]
@dlyash The tests we have in the framework for transactions that use `EmbeddedKafka' do exactly that - i.e., setting that property `transaction.state.log.replication.factor` to 1. I wonder whether we should document that and not make any code changes primarily because retrieving the number of brokers consistently might be challenging. What do you think?

**Comment by sobychacko** [comment]
Ok, you can give it a try and see if that works and is stable. If so, feel free to submit a PR. Thanks!

**Comment by Dltmd202** [comment]
I created fix PR https://github.com/spring-projects/spring-kafka/pull/3602~!
