### ISSUE TITLE
Adding support for direct control over Consumer pause/resume

### ISSUE THREAD

**Issue by javanotes** [spring-projects/spring-kafka#358]
The current usage of consumer pause/resume is based on the backlog in the listener BlockingQueue. However, it is not possible to have a more fine grained control on pausing if needed (by some consumer agent that manages a consumer instance, as part of a framework). Can we have a handle to Consumer directly, or by some other way in order to achieve that.

**Comment by garyrussell** [comment]
The upcoming 2.0 release introduces "consumer-aware" listeners [documentation here](http://docs.spring.io/spring-kafka/docs/2.0.0.BUILD-SNAPSHOT/reference/html/_reference.html#message-listeners) for exactly that purpose.

Since 0.11.0.0 is now available, we are considering repurposing 2.0 to support that (including message headers etc). While it was due to be released next month, adding 0.11 features will cause it to be delayed.

Therefore, we are considering releasing a 1.3 version (supporting kafka 0.10.2.x) next month with the [current 2.0 features](http://docs.spring.io/spring-kafka/docs/2.0.0.BUILD-SNAPSHOT/reference/html/whats-new-part.html#spring-kafka-intro-new).

**Comment by garyrussell** [comment]
That said, the 2.0 branch requires java 8 and it would be difficult to retrofit it to support java 7, so we may be forced to stick with the 2.0 plan of record and add 0.11 support to 2.1.

2.0 is currently in the milestone phase (2.0.0.M2) is [available in the spring milestone repo](http://projects.spring.io/spring-kafka/); the release candidate is due mid-July with GA a couple of weeks later.

**Comment by javanotes** [comment]
Thanks for the information. I don't have an issue with Java 8. Our product has still got some time for a release candidate. Do you suggest I proceed with 2.0.0.M2 for now, or should I wait for the 1.3 GA release?

**Comment by garyrussell** [comment]
I would suggest using 2.0.0.M2 for your dev. work.

**Comment by garyrussell** [comment]
FYI, the 1.3.x effort is now underway (supporting the 0.11 client - headers, transactions); milestone due next week; the 1.3 branch will __not__ support consumer aware listeners because that requires java 8; it will have a subset of the 2.0 features and be released around the same time as 2.0.
