### ISSUE TITLE
Slow batch acknowledging listeners

### ISSUE THREAD

**Issue by tusharm** [spring-projects/spring-kafka#368]
Spring Boot: 1.5.3.RELEASE
Spring Kafka: 1.2.1.RELEASE
JDK: 1.8.0_121
Kafka: 0.10.x

Hi,

This is more of a question/clarification rather than an issue. I am using batch acknowledging listeners (manual offset commit) with `@KafkaListener` annotation. 

I noticed that for batch listeners, the consumer thread hands off the last polled batch to a listener thread, using a BlockingQueue (`recordsToProcess`). I'm investigating the case where the queue gets full and the consumer thread times out trying to push records to it. 

Looking at [this](https://github.com/spring-projects/spring-kafka/blob/1.2.x/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L573), it seems that current batch (B1) will be dropped and Kafka consumer will be polled again for batch B2. Meanwhile, if the queue gets empty, the next batch (B2) will be pushed and subsequently acknowledged by the listener. Wouldn't this result in lost messages (from B1) in Kafka? 

I understand this question is not relevant for Spring Kafka 2.x releases, it's designed differently (there aren't separate consumer/listener threads?). I want to verify if I need to upgrade.

Thx!

**Comment by garyrussell** [comment]
The "current" batch (the one that couldn't be added to the queue is saved in field `unsent` and we `pause()` the consumer. After each subsequent poll (while paused so we won't get any more records) we sent `unsent` to the listener; the consumer is resumed. So, no, messages are not lost.

This crazy logic was needed because Kafka would perform a rebalance when the consumer was too slow because it couldn't tell the difference between a slow consumer and a dead consumer. Heartbeats were tied to polling.

As you have found, the logic in 2.x is much simpler because they fixed the client (in 0.10.1.0 - [KIP-62](https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread)) to handle heartbeats on a different thread, separate from polling. 

We're working on adding 0.11 features to 2.0 (message headers, transactions); we're also considering releasing 1.3.x with just the new threading (and 0.11 features).

**Comment by tusharm** [comment]
Thanks for clearing that @garyrussell! 
I missed that `sendToListener` returns true, when the queue.offer() fails (that's counter-intuitive though, right?), which results in pausing the consumer.
