### ISSUE TITLE
Not working spring configuration

### ISSUE THREAD

**Issue by idyoshin** [spring-projects/spring-kafka#408]
I have faced a problem with spring-kafka 1.2.2  

simple configuration of kafka 

```
@Configuration
@EnableKafka
public class KafkaConfiguration {
}

```

is not working. with this I am facing timeout error on message sends.  

Only with additional `@EnableAutoConfiguration` everything works fine.

**Comment by artembilan** [comment]
Sorry, not enough info.
How can we determine the problem if you don't provide the whole working test-case to play from our side?
Since Spring Kafka advertises `@EnableKafka` for a while already, if that didn't work you would not be a first one who faces the issue.

The `@EnableAutoConfiguration` isn't Spring Kafka project responsibility though...

Please, share as much info as possible to let us to reproduce and fix the problem if that.

**Comment by artembilan** [comment]
Closed as `Invalid` with the leak of responsivity and wrong context.
