### ISSUE TITLE
Multiple consumers with various deserializers

### ISSUE THREAD

**Issue by agrawal93** [spring-projects/spring-kafka#430]
Is it possible to have a configuration in such a manner that we can dynamically generate Consumers with various Key/Value deserializer pair?
For example, let's consider 2 kinds of deserializers: `String` and `ByteArray`.
Now, the brute-force way would be to have 4 kafka listener factories for `String-String`, `String-ByteArray`, `ByteArray-String`, `ByteArray-ByteArray`.
But, this won't scale well for my app. So, I wanted to know if there's a way I can create or use a factory in such a manner that I'm able to create multiple consumers.

I am trying something as follows:
```java
    @Bean
    public Map consumerConfigurations() {  
        Map configurations = new HashMap(); // Will contain some default consumer configurations from application.properties
        return configurations;
    }
    
    @Bean
    public <K, V> ConcurrentKafkaListenerContainerFactory<K, V> kafkaListener(Class<K> keyDeserializer, Class<V> valueDeserializer) {
        Map configurations = consumerConfigurations();
        configurations.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, keyDeserializer);
        configurations.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, valueDeserializer);
        
        ConcurrentKafkaListenerContainerFactory factory = new ConcurrentKafkaListenerContainerFactory();
        factory.setConcurrency(3);
        factory.setConsumerFactory(new DefaultKafkaConsumerFactory<>(configurations));
        factory.getContainerProperties().setPollTimeout(3000);
        return factory;
    }
```
But, with this approach, I'm unable to figure out how to pass the arguments for this. Since, `KafkaListener` only takes `containerFactory` as a `String`.

**Comment by artembilan** [comment]
It really isn't possible because the `@KafkaListener` are really based on the `KafkaListenerContainer`, which, in turn, creates a `KafkaConsumer` based on the provided `configurations`.

So, if you need different `KafkaConsumer`s for different deserializers, there is no choice unless specify different `KafkaListenerContainerFactory` beans and then point `@KafkaListener`'s to them.

The problem that `KafkaListenerContainerFactory` bean must be created prior to the `@KafkaListener` annotation process, not vise versa like you suggest in your post. The original idea is to have one  `KafkaListenerContainerFactory` instance for several `@KafkaListener`s.

**Comment by agrawal93** [comment]
Thank you for your quick response. I guess I'll go with the normal flow.
I'll close the issue. Thanks 👍

**Comment by l0co** [comment]
It looks for me like a kind of not very fantastic design if you have to define new threads just to add another deserializers, while the same thread pool under `ConcurrentMessageListenerContainer` is even able to support multiple topics (but not multiple deserializers). However, this desing might be a result of a design of kafka client internally, since `Deserializer` comes from Kafka client, not from Spring.

This can be, however overcome with a composite pattern by defining some composite deserializer which then delegates to the right deserializer depending on some logic. Spring even provides some `org.springframework.kafka.support.serializer.DelegatingDeserializer` for that. However, it depends on some headers, if you need topic-based choice you have to implement your own.

BTW topic-based composite deserializer would be a nice feature in Spring-Kafka.

**Comment by garyrussell** [comment]
>BTW topic-based composite deserializer would be a nice feature in Spring-Kafka.

https://github.com/spring-projects/spring-kafka/issues/1964
