### ISSUE TITLE
Provide option for stopping consumption on error

### ISSUE THREAD

**Issue by mlueders** [spring-projects/spring-kafka#451]
First off, kudos for a great library!  At my company, we built a `common-kafka` library a while back and I'm going through it now and gutting it, replacing most of the functionality with spring-kafka (which also does a ton more), so thanks!

There's one particular feature of the old library for which I can't seem to find a non-hack solution.  spring-kafka does have support for retries via RetryTemplate but if all retries are exhausted, it sends the error to a handler and then continues going.  For our use case, this is bad.  We use kafka for state propagation, and a missed message equates to corrupted data.  Consider a temporary network failure which prevents communication with the database.  If the outage lasts less than some threshold, the system should recover.  But if it lasts longer, we don't want to just keep processing messages.  We want the container to halt and log an error, at which point monitoring kicks in and a developer gets paged.  If it's a dependency outage (e.g. database), we fix the dependency and restart the app which starts consuming at the last committed offset (which for us, is always immediatelyl after the last successfully processed message).  If it's a poison message, we fix the application and redeploy, but in no case do we drop a message.  I realize a DLQ can be used for this but that introduces it's own complexities so we've opted for the simpler approach of halt, fix and proceed.

I'm currently using `1.2.2.RELEASE` and the hack solution I have is to use a combination of throwing a Throwable from the ErrorHandler and https://projectlombok.org/features/SneakyThrows.  This effectively stops the ListenerInvoker by exiting out of invokeRecordListener/invokeBatchListener and eventually setting active to false in ListenerConsumer.  This is obviously not desirable.

Ideally, there would be a configurable property on ContainerProperties to control whether the container continued after an error or not.  Is there a reason this is not an option or is this open for contribution?

**Comment by artembilan** [comment]
I wonder why don't you consider to use `container.stop()` from error handler or recovery callback.

It's undesirable to introduce such an option to stop after error. That's just doesn't fit to general purpose of messaging: one message failure doesn't effect processing for others.

**Comment by mlueders** [comment]
I disagree that there is a "general purpose of messaging”.  There are use cases and there are solutions which fit those use cases.  In this instance, I am using kafka (messaging) to propagate state from one service to another, in some cases taking action based on that state.  If I lose messages, that state becomes corrupted.  In other words, in this instance, I don’t care about the processing of other messages - I care about the consistency of data.

If what you’re saying is that spring-kafka is not intended to support my use case, I’m good with that, I'll find a work-around/alternative.  If what you’re saying is that my use case is inherently flawed and I should not want to do what I think I want to do, I would appreciate an explanation from your experience or reference documentation on the matter.

Re: the proposed solution of using `container.stop` - based on the `1.2.2.RELEASE` source, it does not seem there is a definitive guarantee that a message would not be 'skipped'.  
Said  another way, does the spring-kafka library make the guarantee that, if `container.stop` is invoked from an error handler or recovery callback thread, then the offset will not have advanced past the previous successfully processed messages for that thread?

**Comment by garyrussell** [comment]
If you are using a batch listener (where the complete contents of the `ConsumerRecords` is sent to the listener in one call) the container will not call the listener again after a stop.

However, If you are using a record listener, the container will, indeed, call the listener with the remaining records; you would have to set some state in your listener to indicate the container is stopping and calls should be ignored.

We should consider adding a `stopNow()`. I am not sure it's a bug per se because the current behavior may be what people want when performing a normal, orderly, stop.

**Comment by mlueders** [comment]
Yes, definitely not a bug - at most, perhaps documentation could be added which explains the specific consumer semantics.  This is more of an 'enhancement request' issue.  

My intent in opening the ticket is to explain a real use case I have which doesn't seem to be supported by the library (at least in the non-happy path) - specifically, one of using kafka for eventually consistent data synchronization across services (without requiring a DLQ and subsequent complexities).  And, if that is a use case which is desirable to support, to brainstorm on specific solutions so that I can contribute an enhancement.  

You are correct in saying that the functionality I desire is supported with the batch listener, but it seems more of an accident of implementation than specifically enforced semantics.  Currently, offsets are processed/committed as the first step in the polling loop (looking at KafkaMessageListenerContainer:ListenerConsumer.run).  If offsets were processed as the last step, then this would no longer hold.  Processing the commits as the first step also means (I believe) that I could have a listener which processes and entire batch successfully but for which the offsets are never committed b/c the container is closed around the same time as the listener returns.  So I could envision a future change which moves commit handling after message processing.  Not saying it will happen, there could very well be other reasons which make that undesirable, just explaining why I'm reticent to rely on undocumented implementation details.

In any case, it does not work in today's implementation for a record listener and I would like to talk about potential implementations where it could.  Some possibilities...
1. `stopNow()` on a container.  Given the multi-threaded nature of the listener container, this seems a bit odd to me.  Specifically, the semantics of `stopNow` would need to change, depending on the invoking thread.  When invoked on the message listener thread, it would need to guarantee that no further offsets are committed after the last successfully processed message for partitions which the current thread is assigned.  When invoked from some other thread, it would probably have the same semantics as the current `stop()`.
2. A configurable option on ContainerProperties which allows the user to specify what they want to happen when an exception is thrown (continue processing or close the consumer at the moment of the unprocessable message/batch)
3. A specific exception thrown by the message listener (e.g. StopProcessingException) which does the same thing as #2 but is an exception propagated by the listener rather than an option of ContainerProperties.
4. ???

Thoughts?

**Comment by artembilan** [comment]
@mlueders ,

Thank you very much for such a thorough and patient discussion!

Well, I think the idea about specific exception really makes sense here.
More over we have similar solution already in Spring AMQP: https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/exception/FatalListenerExecutionException.java

Which is used in the `SimpleMessageListenerContainer` like:
```
catch (FatalListenerExecutionException ex) {
	logger.error("Consumer received fatal exception during processing", ex);
	// Fatal, but no point re-throwing, so just abort.
	aborted = true;
	publishConsumerFailedEvent("Consumer received fatal exception during processing", true, ex);
}
```
Seems for me similar approach, plus a `ListenerContainerConsumerFailedEvent`, should be fully sufficient for your use case.

@garyrussell , WDYT?

**Comment by mlueders** [comment]
I agree, the exception solution would definitely fit my use case, and it seems better than the alternatives since it applies consistency across spring libraries.

@artembilan can you elaborate on the implementation details in Spring AMQP?  Specifically, what happens when there are multiple consumers?  In the context of kafka-spring, handling the exception in KafkaMessageListenerContainer is straight forward - commit the offset of the last successfully processes message before the exception is thrown and stop consuming.  However, what about ConcurrentMessageListenerContainer?  Should a ‘stop’ exception thrown from one container halt all containers or just the one?

It seems there are two main scenarios - 1. there is a transient error that persists long enough on one of the containers to fail max retries and 2. there is a poison message.  My initial thought is to only stop the container which throws the ‘stop’ exception.  If it’s a transient error, then the other containers would keep processing though with diminished overall capacity.  If it’s a poison message, the other containers would eventually die since they would all throw the exception once they got to that message.

**Comment by SteluHH** [comment]
Hi all,

I am interestingly following this discussion and really don't want to pollute here, but maybe I can also give one thought about this. In the last weeks I was as well integrating Spring Kafka in a Microservice application and I was standing in front of the exact same challenge. 
I ended up with a solution using a Dead Letter Queuing as suggested by @garyrussell on [stackoverflow](https://stackoverflow.com/questions/45883794/kafka-consumes-unprocessable-messages-how-to-reprocess-broken-messages-later) by just transferring all broken messages (more specific: not processable) to a topic that acts as a parkinglot. 

Nevertheless I would definately agree for the necessity of stopping message consumption totally in order to prevent further damage. Since the Dead letter queueing solution might fail as well because of simple implementation bug there is then the need to basically stop kafka event consumption completely. For example we will be using Spring Kafka to process messages in a Onlineshop order processing environment and the customer would lose hundret thousands of euros if a particular message would get lost continously - so there is the need to make this as failsafe as possible, which also includes the necessity to shut down the consumer in certain fatal application error scenarios.

Kind regards,

Stef

**Comment by artembilan** [comment]
Thank you guys, for the valuable feedback!

To be honest I don't see the whole solution yet. So, let's go with simple steps!

In Spring AMQP the logic is like:
```
if (aborted) {
	logger.error("Stopping container from aborted consumer");
	stop();
}
```
independently of its `concurrency`. And I really would say that it is natural to stop the whole `ConcurrentMessageListenerContainer` because from the application perspective it is a single entity.

However at the same time we could introduce something like `FailedListenerExecutionException` to stop only container with "guilty" listener. Although not clear how to restart it afterwards...

BTW, there is also an option like:
```
/**
	 * Set whether or not the container should commit offsets (ack messages) where the
	 * listener throws exceptions. This works in conjunction with {@link #ackMode} and is
	 * effective only when the kafka property {@code enable.auto.commit} is {@code false};
	 * it is not applicable to manual ack modes. When this property is set to {@code true}
	 * (the default), all messages handled will have their offset committed. When set to
	 * {@code false}, offsets will be committed only for successfully handled messages.
	 * Manual acks will always be applied. Bear in mind that, if the next message is
	 * successfully handled, its offset will be committed, effectively committing the
	 * offset of the failed message anyway, so this option has limited applicability.
	 * Perhaps useful for a component that starts throwing exceptions consistently;
	 * allowing it to resume when restarted from the last successfully processed message.
	 * @param ackOnError whether the container should acknowledge messages that throw
	 * exceptions.
	 */
	public void setAckOnError(boolean ackOnError) {
```

We also may reconsider the `processCommits();` order.

**Comment by pkfka** [comment]
Let's say I have a batch listener (@Transactional specified) and receives 100 messages. When processing these messages, I might fail on only 10 of the 100 messages. Is there a way to selectively NOT acknowledge those messages so that only those 10 will be delivered again. Right now, because I have defined @Transactional, it is all or none I think. If there is any exception, I am stopping using kafkaListenerEndpointRegistry.stop(); and everything gets delivered when I restart listener.

Also, second part of the question is, when do I do kafkaListenerEndpointRegistry.start() after I stop. without restarting the listener
