### ISSUE TITLE
why the BatchErrorHandler extends GenericErrorHandler<ConsumerRecords<?, ?>> ranther than GenericErrorHandler<List<ConsumerRecords<?, ?>>>

### ISSUE THREAD

**Issue by wangfucai** [spring-projects/spring-kafka#459]
Hi, now I'm looking the `KafkamessageListenerContainer`, I see the private class `ListenerConsumer` have the fields have the `MessageListener<K, V> listener` and `BatchMessageListener<K, V> batchListener`, the two filed extends `GenericMessageListener` interface. The difference lies in the extends template One is `ConsumerRecord<K, V>`， the other is `List<ConsumerRecord<K, V>>`, the same as `ErrorHandler errorHandler` and `BatchErrorHandler batchErrorHandler`, why the two field are all extended `GenericErrorHandler<ConsumerRecord<?, ?>>`? By personal understanding the `BatchErrorHandler` should extends `GenericErrorHandler<List<ConsumerRecord<?, ?>>>`

**Comment by artembilan** [comment]
The `BatchErrorHandler` does exactly this:
```
public interface BatchErrorHandler extends GenericErrorHandler<ConsumerRecords<?, ?>> {
```
That is `ConsumerRecords` not a single `ConsumerRecord`.

This one doesn't deal with the `List<ConsumerRecord<?, ?>>` because it is an error and would be good to have there as low data of failure as possible.

The `ConsumerRecords` isn't so good for the target high-level `@KafkaListener` API, because that would be better to make as less Kafka-dependant as possible. That's why we provide there a `List<ConsumerRecord<?, ?>>`, which, essentially, is converted to the `List<Message<?>>` or `List<Object>` for the target business logic.

We might could have the `BatchMessageListener` as a `ConsumerRecords` in its generics as well, but that technically doesn't bring to the target conversion logic too much. The `BatchErrorHandler` has been introduced lately.

**Comment by garyrussell** [comment]
The main reason the batch listener gets a `List` rather than a `ConsumerRecords` is so the filtering adapter can remove individual messages; we can't do that with `ConsumerRecords`.
