### ISSUE TITLE
Backport 'Upgrade to kafka-clients 1.0.0' to 1.3.x branch

### ISSUE THREAD

**Issue by lazystone** [spring-projects/spring-kafka#471]
Would it be possible to add support for Kafka 1.0.0 in 1.3 branch?

#469 #468

**Comment by garyrussell** [comment]
If you are not using the `KafkaEmbedded` from `spring-kafka-test`, it should just work by overriding the kafka-clients version.

The `KafkaEmbedded` broker won't work because they made some API changes; we'd have to create a 1.4 for that; we already have a lot of versions to maintain because the API was so volatile between 0.9.0.0 and 1.0.0; so I am wary of adding yet another branch,

**Comment by lazystone** [comment]
We actually do use KafkaEmbedded from spring-kafka-test. It just would be nice to have something which works with Spring Boot 1.x and Kafka 1.0.0

**Comment by garyrussell** [comment]
I'll see if I can come up with a way to make 1.3 work with 0.11 and 1.0; if I can't figure something out quickly, we'll need to create a 1.4 branch.

**Comment by garyrussell** [comment]
Wasn't too bad, but the pom is a bit ugly.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-kafka/commit/6b925914c6750c6ec6beb5fb3cbac8d3a15f8437
