### ISSUE TITLE
Kafkalistener consumes messages before spring application starts 

### ISSUE THREAD

**Issue by Ilamuruguv** [spring-projects/spring-kafka#475]
Hi,

i am using the kafka listener annotation to consume the message, 

```java
 @KafkaListener(topics = "${kafka.consumer.topic}", containerFactory = "kafkaListenerContainerFactory") 
```
then trying to post the message to an camel route endpoint. 

```java
try {
            ProducerTemplate prodTemplate = camelContext.createProducerTemplate();
            prodTemplate.sendBody(kafkaConsumerStartProcessEndPoint, msg);
        } catch (CamelExecutionException camelExecutionException) {
            throw camelExecutionException;
        }
```

the problem is,  kafka listener consumes the messages from the topic before the spring application starts the camel routes.   it is failing with camel n o end points. 

how do i make the kafka listener consume the messages after the spring application ready?

**Comment by artembilan** [comment]
Please, consider to study how properly comment on GitHub: https://help.github.com/articles/basic-writing-and-formatting-syntax/
It's hard to read that blurred code.

See this: https://jira.spring.io/browse/INT-3475 as an explanation.

The `KafkaListenerEndpointRegistry` for the `@kafkaListener` annotation has this as default:
```
private int phase = Integer.MAX_VALUE;
```
However we have an inconsistency here with the `AbstractMessageListenerContainer`:
```
private int phase = 0;
```
Therefore we override that value in the `KafkaListenerEndpointRegistry`:
```
	int containerPhase = listenerContainer.getPhase();
		if (containerPhase < Integer.MAX_VALUE) {  // a custom phase value
			if (this.phase < Integer.MAX_VALUE && this.phase != containerPhase) {
				throw new IllegalStateException("Encountered phase mismatch between container factory definitions: " +
						this.phase + " vs " + containerPhase);
			}
			this.phase = listenerContainer.getPhase();
		}
```
and start all the listener container too early.

Just my best guessing because we don't see any logs from you how that Camel context is started.

When you declare `KafkaListenerContainerFactory` `@Bean` you can override its phase to the `Integer.MAX_VALUE` to start listener containers as late as possible.

OTOH you always can do `factory.setAutoStartup(false);` and start containers via injected `KafkaListenerEndpointRegistry` later on demand.

Confirm, please, such a behavior and we will proceed with the fix for the mentioned inconsistency.

**Comment by Ilamuruguv** [comment]
thanks artembilan !  It is resolved now  with the factory.setAutoStartup(false);  and injected the KafkaListenerEndpointRegistry start after the application started with all the camel routes. 

thanks,
Ila.

**Comment by artembilan** [comment]
I still think that we have to fix that overriding from `Integer.MAX_VALUE` to `0` for consistency and really for the fact to start consume Kafka as late as possible.

**Comment by srinivasvsk** [comment]
Hi, Was just about to open similar issue. We are seeing similar behavior,  the listener is processing messages much before the /health endpoint is up too.  If there are lot of pending messages, it takes a while.
