### ISSUE TITLE
SpEL not supported for containerFactory on KafkaListener annotation ?

### ISSUE THREAD

**Issue by SamD** [spring-projects/spring-kafka#644]
I previously had an expression that works fine when setting topics; however, when I recently tried to update the containerFactory to use an expression as well it fails.

```java
    @KafkaListener(topics = "#{appArguments.getTopic()}", containerFactory = "#{appArguments.getConsumerTypeFactory()}")
```
Here topics is resolved but for containerFactory I get:
```java 
no KafkaListenerContainerFactory with id '#{appArguments.getConsumerTypeFactory()}' was found in the application context;
```
where hardcoding works.

Using
org.springframework.boot:spring-boot-gradle-plugin:2.0.0.RELEASE
org.springframework.kafka:spring-kafka:2.1.4.RELEASE

**Comment by artembilan** [comment]
That's correct. It must support SpEL (or even just properties placeholder resolver). Just because it is about a `bean name`, not about something resolved at runtime. Not telling that there was just no such a request, but for consistency with other similar approaches throughout Spring Portfolio, this kind of attributes are for static values - exact bean names.

you can expose your `appArguments.getConsumerTypeFactory()` as a bean and use its name for the `@KafkaListener`.

Otherwise consider to use `KafkaMessageListenerContainer` directly instead of annotation configuration. It really has restricted abilities.

I'm fully against support SpEL in bean names attributes in annotations.

**Comment by SamD** [comment]
@artembilan Great, thanks for the detailed response and suggestion. I wanted a listener on the same topic which possibly could alter the factory as in one case it may require a StringDeserializer and another JSON.

**Comment by SamD** [comment]
@artembilan on a side node, is it possible to use `@KafkaListener` in a way to set the listener to be an `AcknowledgingMessageListener` ?
