### ISSUE TITLE
AfterRollbackProcessor called with all unprocessed records in case of a Record Listener

### ISSUE THREAD

**Issue by mawri** [spring-projects/spring-kafka#698]
While using a record listener, ``AfterRollbackProcessor`` is invoked with all the unprocessed record - https://github.com/spring-projects/spring-kafka/blob/04110a6b4f3f5951f84a24d383347cceb52717e7/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1039

Should it not be invoked with only the record for which there is an error processing?

**Comment by garyrussell** [comment]
Please don't use GitHub issues to ask questions; they are for reporting bugs and asking for new features. Use Stack Overflow or Gitter for questions.

No; see the `DefaultAfterRollbackProcessor` - it re-seeks for all topics in the unprocessed records list so that they are all re-fetched (including the failed record) on the next poll.

**Comment by mawri** [comment]
Sorry for asking here. I will move this to gitter.
