### ISSUE TITLE
Easy POJO to JSON serialization (and back)

### ISSUE THREAD

**Issue by stepio** [spring-projects/spring-kafka#79]
I've implemented (de)serialization for POJO messages as a separate project:
https://github.com/stepio/kafka-json

In my opinion it's too tiny to be supported as a separate functionality, but it would be nice as a part of Spring Kafka.
What do you think? If you agree on this, what package would you suggest?

**Comment by garyrussell** [comment]
Thanks @stepio - while the project currently has JSON support vis the `StringJsonMessageConverter`, I agree it would be nice to include this in the project. I would say the new package should be `o.s.k.support.serializer`.

Please be sure to follow the [contribution guidelines](https://github.com/spring-projects/spring-kafka/blob/master/CONTRIBUTING.adoc), especially "signing" the CLA, "Spring Kafka" doesn't currently appear in the drop down, but you can use "Spring Integration". Also take note of the code formatting needed (license header etc).

Please note that we are planning to release the release candidate next Monday or Tuesday, so a quick turnaround would be very helpful. However, since this is just new code and not changing existing, we can add it after the candidate is released and still get it in the final release.

Thanks !!

**Comment by stepio** [comment]
Looks good for me, thanks!

**Comment by artembilan** [comment]
The PR #81 has been merged and closed
