### ISSUE TITLE
Spring Kotlin with Kafka utilizing @SendTo does not properly work with Springs- Kotlin property substitution

### ISSUE THREAD

**Issue by meshpaul** [spring-projects/spring-kafka#847]
🐞 Bug report

Hi,

While working with Spring Boot, Kotlin, Spring Kafka and utilizing Springs Request Reply template

 kotlinVersion = '1.2.61'
    springBootVersion = '2.0.5.RELEASE'
    springCloudVersion = 'Greenwich.BUILD-SNAPSHOT'
    gsonVersion = '2.8.5'
    commonsValidatorVersion = '1.4.1'
    libphonenumberVersion = '5.5'
    log4jVersion = '2.11.1'
    junitVersion = '4.12'
    protobufGradlePluginVersion = '0.8.6'
    springKafkaVersion = '2.1.10.RELEASE'
    commonsValidatorVersion = '1.4.1'
    jacksonModuleKotlinVersion = '2.9.6'
    javaVersion='1.8'
I have stumbled upon an issue here is scenario thats easily replicated

Using Spring KafkaRequestReplyTemplate set up a required client call to REQ/REPLY topics
Using Listener to receive required messages on REQ topic and once received send them to REPLY topic via @SendTo the value in @SendTo is as follows
     @KafkaListener(topics = ["\${my.input-request-topic}"])
    @SendTo("\${my.output-reply-topic}")
    override fun caseRequestListener(myModel: CommandModel): CommandModel {
       logger.warn("SUCCESS RECIVED MESSAGE {} ", myModel)

       myModel.responseType = CommandModel.ResponseType.SUCCESS

        return myModel

    }
the above property definition in @SendTo does not resolve and kept as is ${my.output-reply-topic}.

The only way this works if I use static declarations or change to use Spring EL using #{ and not Kotlin supported \${myVal}... I also tried git issue with custom property resolver that did not work... what works is something like this :
@SendTo("#{systemProperties['my.output-response-topic'] ?: 'MY.CMD.CREATE.RESPONSE'}")

**Comment by garyrussell** [comment]
It's not just Kotlin - we don't currently resolve property placeholders at all.

**Comment by garyrussell** [comment]
The [documentation](https://docs.spring.io/spring-kafka/reference/html/_reference.html#annotation-send-to) clearly states what is supported iin `@SendTo`

The @SendTo value can have several forms:

* @SendTo("someTopic") routes to the literal topic
* @SendTo("#{someExpression}") routes to the topic determined by evaluating the expression once during application context initialization.
* @SendTo("!{someExpression}") routes to the topic determined by evaluating the expression at runtime. The #root object for the evaluation has 3 properties:
  * request - the inbound ConsumerRecord (or ConsumerRecords object for a batch listener))
  * source - the org.springframework.messaging.Message<?> converted from the request.
  * result - the method return result.
* @SendTo (no properties) - this is treated as !{source.headers['kafka_replyTopic']} (since version 2.1.3).

What led you to believe property placeholders are supported.

(I am not saying we shouldn't support it, however).
