### ISSUE TITLE
RecordFilterStrategy is not called for listeners consuming ConsumerRecord

### ISSUE THREAD

**Issue by martin-mucha** [spring-projects/spring-kafka#854]
When `@KafkaListener` accepts `ConsumerRecords<String, SomeClass>` records as a parameter, defined `factory.setRecordFilterStrategy(new RecordFilterStrategy<String, SomeClass>() {` is not called. However if we change listener to accept `List<SomeClass>`, filter will be called. It seems little bit counterintuitive and I did not see this anywhere documented. Anyways, I don't see the reason, why "should do the filtering" should be dependent on type in listener...

**Comment by garyrussell** [comment]
The ability to support consuming `ConsumerRecords` instead of `List<ConsumerRecord>` (or `List<Something>`) was added later (as a user request).

`ConsumerRecords` is immutable; hence the filter is not called.

The doc...

>Starting with version 2.2, the listener can receive the complete `ConsumerRecords<?, ?>` object returned by the `poll()` method,

... kind of implies that "the complete", but I suppose it could be clearer.

I suppose we could call it, but the `FilteringBatchMessageListenerAdapter` would have to construct a completely new `ConsumerRecords`.

Contributions are welcome.

**Comment by garyrussell** [comment]
BTW, there already is a warning logged if so configured:

```java
if (this.logger.isWarnEnabled()) {
	this.logger.warn("Filter strategy ignored when consuming 'ConsumerRecords'"
			+ (this.id != null ? " id: " + this.id : ""));
}
```

**Comment by garyrussell** [comment]
Docs updated.
