### ISSUE TITLE
how can i set offset by myself

### ISSUE THREAD

**Issue by dragontree101** [spring-projects/spring-kafka#89]
now i find `recent-offset` can set offset from end message
if i want to consumer message from offset=100 but i don't know what is the lastest offset, so i can't use  `recent-offset`
but i doesn't find any way to set offset=100 use spring-kafka by myself.
how can i set offset by myself? thanks

**Comment by garyrussell** [comment]
It's not currently supported - we can consider adding an option but the problem is you don't really know what the broker has retained. We thought the recent offset would be useful to get, say, the last message in a topic after starting, even if you've previously received it. We didn't envision a need for positioning `n` messages from the beginning of whatever the broker has retained.

Can you explain your use case, and we'll consider adding it.

[Contributions are always welcome too](https://github.com/spring-projects/spring-kafka/blob/master/CONTRIBUTING.adoc).

**Comment by dragontree101** [comment]
we have this case: 
every day we have produce some order messages(related to money)
and next day we want to re consumption these order messages to reconciliation
we will recode offset to db at the begin of day, and a crontab to re consumption these order messages to reconciliation
