### ISSUE TITLE
Not able to read the same message again when i do not commit offset.

### ISSUE THREAD

**Issue by saroj8807** [spring-projects/spring-kafka#898]
Hi Team,

I have created a Kafka consumer with below properties:

spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=MANUAL (Also tried with MANUAL_IMMEDIATE)

Here is how my consumer code looks like:

	@KafkaListener(topics = "${kafka.sanity.topic.name}")
	public void receive(ConsumerRecord<?, ?> consumerRecord, Acknowledgment acknowledgment) {
		logger.info("consumption successful. partition={}, offset={}, \n\n", consumerRecord.partition(),
				consumerRecord.offset());
		// acknowledgment.acknowledge();
	}

As you can see, i have commented "acknowledgment.acknowledge();" that means i am not committing the offset and auto-commit is also set to false but still every time i am receiving the new message.

My understanding was if i do not commit the offset (incase any exception occurred etc...) then when poll() happens i will get the same message again. Please correct me if my understanding is wrong ??

And if this is the expected behavior then what is the purpose of manually committing offset ?

Just to summarize, whether i do "acknowledgment.acknowledge()" or not, i am always getting the latest messages.

Thanks,
Saroj

**Comment by garyrussell** [comment]
Did you not read the issue instructions? Issues are not for asking questions.

>🙅 "Please DO NOT Raise an Issue" Cases
>- Question
STOP!! Please ask questions about how to use something, or to understand why something isn't
working as you expect it to, on Stack Overflow using the spring-kafka tag.

Not committing the offset does not tell kafka to send it again on the next `poll()` (unless the consumer is stopped and restarted). Furthermore, we may have pre-fetched more records past the failed one so you will get those, by default, before the next poll is performed.

In order to get the same message redelivered, you need to throw an exception and use a (`SeekToCurrentErrorHandler`](https://docs.spring.io/spring-kafka/reference/html/_reference.html#seek-to-current) (since version 2.0.1). The framework will perform seeks to all unprocessed messages will be redelivered by the next `poll()`.

With earlier versions you have to stop/restart the container in the error handler.

>And if this is the expected behavior then what is the purpose of manually committing offset ?

It gives you a bit more control but, to be honest, should only be used for unusual use cases.
