### ISSUE TITLE
No Partition/Offset-Information in ErrorHandler if records is null/empty

### ISSUE THREAD

**Issue by hp-dwp** [spring-projects/spring-kafka#903]
I use a ConsumerAwareErrorHandler in order to skip unreadable/broken AVRO-messages.
If the deserializer throws a SerializationException, the supplied ConsumerRecord argument (data) is null. Since this record is the only source of partition information I cannot skip this message using consumer.peek.

**Comment by garyrussell** [comment]
Please provide more information - spring-kafka version; configuration etc; even better a small example that exhibits the behavior.

I don't see how it's possible to get a `null` `ConsumerRecord`.

Regardless, the error handler doesn't need access to the offset to skip a record. When an error handler "handles" an error, by exiting normally, the offset is committed.

But, of course, if the record is really null, the container won't be able to commit it either.

**Comment by hp-dwp** [comment]
Sorry, I'm using spring-kafka 2.1.7.

In org.springframework.kafka.listener.KafkaMessageListenerContainer.ListenerConsumer.run(), when consumer.poll(...) throws a SerializationException, this Exception is handled by 'handleConsumerException(...)', which in turn invokes the errorHandler routines with either an empty record list or null.
`{
@FunctionalInterface
public interface ConsumerAwareErrorHandler extends ErrorHandler {

	@Override
	default void handle(Exception thrownException, ConsumerRecord<?, ?> data) {
		throw new UnsupportedOperationException("Container should never call this");
	}

	@Override
	void handle(Exception thrownException, ConsumerRecord<?, ?> data, Consumer<?, ?> consumer);

	@Override
	default void handle(Exception thrownException, List<ConsumerRecord<?, ?>> data, Consumer<?, ?> consumer,
			MessageListenerContainer container) {
		handle(thrownException, null, consumer);
	}

}
}`

**Comment by hp-dwp** [comment]
I didn't want to close this issue. Think thumb I guess.

**Comment by garyrussell** [comment]
Ah, I see; yes, of course; in that case, there is nothing we can do to help here because the exception is thrown within the Kafka Client itself.

To address this issue, in 2.2.x, we added the `ErrorHandlingDeserializer` (and improved it in 2.2.1 with `ErrorHandlingDeserializer2`.

With that in place (it wraps the actual deserializer); it catches the exception and returns the information about the deserialization exception in a header.

The listener container detects the presence of that header and invokes the error handler directly, instead of calling the listener.

See [the documentation](https://docs.spring.io/spring-kafka/reference/html/_reference.html#error-handling-deserializer).

**Comment by hp-dwp** [comment]
Thanks, we will get back to that when we switch to the latest version (which unfortunately will take a while).
I was thinking about asking the Kafka-team to improve their SerializationException by adding offset and partition, since the information is there, it's just not propagated. You think this would make sense?

**Comment by garyrussell** [comment]
Unfortunately, the deserializer API doesn't provide access to the topic/partition/offset during deserialization so the code that invokes the deserializer would have to be modified. It certainly won't hurt to ask.

One immediate solution for you would be to copy the `ErrorHandlingDeserializer2` from 2.2.

While the listener container won't detect the exception and route directly to the EH, there are a couple of options; depending on what your `@KafkaListener` looks like.

1. If it's `listen(MyObject foo)` an exception will be thrown since foo will be null; this exception will go to the error handler.
2. If it's `listen(@Payload(required = false) MyObject foo)`, foo will be passed to the listener as `null` (you could also access the deserialization exception in a `@Header` param).
3. if it's `listen(ConsumerRecord<?, Foo> record)`, `record.value()` will be null (and the deserialization information will be in the headers.

**Comment by hp-dwp** [comment]
I'll give it a try, thank you again.
