### ISSUE TITLE
Random generated group id

### ISSUE THREAD

**Issue by JBertaux** [spring-projects/spring-kafka#906]
Hello,

I am here to propose a new feature because I didn't find an easy solution to do it. I would like to have the Kafka group id be generated by Spring Kafka when I don't provide one, like for the annotation `@StreamListener` in Spring Cloud Stream. It would be a nice feature when we have multiple instances of the same application and we want that each applications receive the same Kafka message. 
In the following example, I would like that Spring Kafka generates for me the group id  : 
```java
    @KafkaListener(topics = "my-topic")
    public void handleMessage(String message){
        System.out.println(message);
    }
```

Do you think this is a good idea ?

**Comment by artembilan** [comment]
Not sure if we are going to implement this here since you simple can provide a random value for the `group.id` property configuring `DefaultKafkaConsumerFactory` and also using Spring Boot you can do something like this:
```
spring.kafka.consumer.group-id=${random.uuid}
```
Does it work for you?

We can't compare a general Spring for Apache Kafka project with the Spring Cloud Stream Kafka Binder. The last one is fully based on Spring Cloud with a strong opinion about configuration and environment.
And there is definitely built-in anonymous scenario there. Meanwhile the first one is just a convenient API around standard Apache Kafka client. And since Apache Kafka per se doesn't advertise random group id, I don't find it as a strong requirement for this Spring for Apache Kafka as well.

Hope that helps.

**Comment by garyrussell** [comment]
You can also do it in the annotation `groupId = "#{T(UUID).randomUUID().toString()}`.

**Comment by artembilan** [comment]
Oh! I forgot that it is a SpEL expression. So, let's close this one with a simple sentence in the Docs how the SpEL feature can be used on that  `groupId` property! 😄

**Comment by JBertaux** [comment]
I didn't know that the property `groupId` accepts SpEL. I searched in the Javadoc and nothing was mention:
```java
	/**
	 * Override the {@code group.id} property for the consumer factory with this value
	 * for this listener only.
	 * @return the group id.
	 * @since 1.3
	 */
	String groupId() default "";
``` 
Thanks for the quick reply, it is exactly what I need ! Sorry for the inconvenience.

**Comment by garyrussell** [comment]
We'll fix the docs/javadocs

**Comment by jjustman** [comment]
> `#{T(UUID).randomUUID().toString()}`.

The correct annotation with SPEL is:

	@KafkaListener(topics = "topic-notification", groupId = "#{T(java.util.UUID).randomUUID().toString()}")
