### ISSUE TITLE
Add option to receive an empty list (or ConsumerRecords) when a poll returns no records

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#939]
Batch listeners only; false by default in 2.2, true in 2.3.

**Comment by garyrussell** [comment]
Another thought - 

```java
/**
 * Message listeners that also implement this interface will be notified when
 * a poll returned no messages.
 * 
 * @author Gary Russell
 * @since 2.1.4
 *
 */
public interface NoRecordsPolledReceiver {

	void onNoMessagesReceived();
	
}
```

Then all listeners, not just batch listeners can be notified.

WDYT @artembilan ?

However, I am not sure it adds much value over `@EventListener` for idle events.

Only providing a "solution" for batch listeners is not very appealing to me, so I am thinking of closing this as `declined`.

**Comment by kobynet** [comment]
@garyrussell I just came across such use-case, we have a kafka listener which should batch messages (in-memory)until a certain threshold is reached,once the threshold is reached(for example certain size in bytes), we should create batch insert to some db.

Binding kafka max fetch records to the db batch size is problematic since we have some filtering logic and we might end up in small batches which is far from optimal in our case.

using ListenerContainerIdleEvent is also problematic since it can run on a different thread and therefore we cannot use it's  consumer for commiting offsets due to race condiiton. also synchonizing the threads won't work either because we might end with race condition between the kafka listener handler method and the Let's close it in favor of ListenerContainerIdleEvent.

It actually seems like a pretty trivial use case for a message container which is in charge of batching data for sending it to sink database.

I believe for such use-cases kafka consumer itself do support invoking handler with empty records list, any thoughts how we might solve this?

**Comment by garyrussell** [comment]
>it can run on a different thread 

Only if you change the application context's default event dispatcher; otherwise it will always be called on the consumer thread.
