### ISSUE TITLE
Option to commit offsets when publishing to dead letter topic.

### ISSUE THREAD

**Issue by miklesw** [spring-projects/spring-kafka#990]
**Affects Version(s):**  latest

When max retries is reached, the DefaultAfterRollbackProcessor uses seek to skip the failing record. This means that the record will be processed when the app is restarted.

To work around this I extended the DeadLetterPublishingRecoverer to also commit the offset.

Alternatively the DefaultAfterRollbackProcessor could be configured to commit the offsets after rolling back the main transaction.

https://stackoverflow.com/questions/55023117/kafkatemplate-in-transactional-kafkalistener-publishes-messages-when-transaction

```
@Transactional(KAFKA_TRANSACTION_MANAGER)
class OffsetCommittingAndDeadLetterPublishingRecoverer(val template: KafkaTemplate<Any, Any>) :
    DeadLetterPublishingRecoverer(template) {

    override fun accept(record: ConsumerRecord<*, *>, exception: Exception) {
        super.accept(record, exception)

        val topicPartition = TopicPartition(record.topic(), record.partition())
        val offsetAndMetadata = OffsetAndMetadata(record.offset() +1)

        template.sendOffsetsToTransaction(
                mapOf(topicPartition to offsetAndMetadata)
            )
        }
}
```

**Comment by anschnapp** [comment]
Sorry to write to this already closed ticket, if you think i should open a new one please let me know.

But my problem fits perfectly to the title of this issue. So i want to have an explicit commit after a dead letter was send. I want to avoid sending a dlq duplicate (or more if the are in a row)  after a consumer restart.

I'm not sure if the solution inside of DefaultAfterRollbackProcessor works for me.
Because it seems that this solution is only for circumstances where kafka transactions are used.
Which is not the case in my scenario. I have a quite simple setup (but with manual direct offset) where i want commit after each processed entry (even on dlq handled ones).

**Comment by garyrussell** [comment]
Commenting on old, closed, issues is not a good idea; especially when unrelated since you are not using transactions.

The default behavior in supported versions is to commit the offset after an error handler successfully "handles" the error - see `CommonErrorHandler.ackAfterHandle()`. 

If you are seeing different behavior, open a new issue, providing a minimal, complete, reproducible example.

**Comment by anschnapp** [comment]
Thanks for answering @garyrussell 

You are right that this is not the best place.
Yes the topic is slightly different but the title was a complete fit and also most of the description (until the example appears ;))

But if i might ask you one more question:

I use the DefaultErrorHandler with an DeadLetterPublishingRecoverer inside.
I now have used `defaultErrorHandler.setAckAfterHandle(true);` inside my configuraiton.

I have a integration test and it seems like there is no commit / ack for a dead letter "recovered" entry.
Do you might have another clue for me, why this does not work?
(i tried to looked up inside the implementation but i didn't even find a usage for `isAckAfterHandle`...)

**Comment by garyrussell** [comment]
`ackAfterHandle` is true by default so no need to set it.

https://github.com/spring-projects/spring-kafka/blob/8a23e479a1e43ee6f7adc4a8994e0bb6ba05a8cb/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2730-L2731

and

https://github.com/spring-projects/spring-kafka/blob/8a23e479a1e43ee6f7adc4a8994e0bb6ba05a8cb/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2750-L2764
Bear in mind that the actual commit depends on the `AckMode` if the default, `BATCH` is used, the commit won't happen until the remaining records from the poll have been processed. To commit immediately, use `AckMode.RECORD`.

https://github.com/spring-projects/spring-kafka/blob/8a23e479a1e43ee6f7adc4a8994e0bb6ba05a8cb/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L2940-L2966
